//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewBisPA.smsSvcRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Param_SMS", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Param_SMS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<long> ZTB_SMS_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MESSAGEField;
        
        private System.Nullable<long> ZTB_ORG_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OFFICEField;
        
        private System.Nullable<System.DateTime> SEND_DTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SEND_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SENDING_STATUSField;
        
        private System.Nullable<System.DateTime> UPD_DTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ERR_CODEField;
        
        private System.Nullable<long> ZTB_SMS_TYPE_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SENDER_NAMEField;
        
        private System.Nullable<long> APPLICATION_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ERR_MESSAGEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NewBisPA.smsSvcRef.SMS_POLICY_SENDING SMS_POLICY_SENDINGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NewBisPA.smsSvcRef.SMS_RECIPIENT_PERSON[] SMS_RECIPIENT_PERSON_CollectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NewBisPA.smsSvcRef.SMS_REFERENCE[] SMS_REFERENCE_CollectionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<long> ZTB_SMS_ID {
            get {
                return this.ZTB_SMS_IDField;
            }
            set {
                if ((this.ZTB_SMS_IDField.Equals(value) != true)) {
                    this.ZTB_SMS_IDField = value;
                    this.RaisePropertyChanged("ZTB_SMS_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MESSAGE {
            get {
                return this.MESSAGEField;
            }
            set {
                if ((object.ReferenceEquals(this.MESSAGEField, value) != true)) {
                    this.MESSAGEField = value;
                    this.RaisePropertyChanged("MESSAGE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<long> ZTB_ORG_ID {
            get {
                return this.ZTB_ORG_IDField;
            }
            set {
                if ((this.ZTB_ORG_IDField.Equals(value) != true)) {
                    this.ZTB_ORG_IDField = value;
                    this.RaisePropertyChanged("ZTB_ORG_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string OFFICE {
            get {
                return this.OFFICEField;
            }
            set {
                if ((object.ReferenceEquals(this.OFFICEField, value) != true)) {
                    this.OFFICEField = value;
                    this.RaisePropertyChanged("OFFICE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<System.DateTime> SEND_DT {
            get {
                return this.SEND_DTField;
            }
            set {
                if ((this.SEND_DTField.Equals(value) != true)) {
                    this.SEND_DTField = value;
                    this.RaisePropertyChanged("SEND_DT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string SEND_ID {
            get {
                return this.SEND_IDField;
            }
            set {
                if ((object.ReferenceEquals(this.SEND_IDField, value) != true)) {
                    this.SEND_IDField = value;
                    this.RaisePropertyChanged("SEND_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string SENDING_STATUS {
            get {
                return this.SENDING_STATUSField;
            }
            set {
                if ((object.ReferenceEquals(this.SENDING_STATUSField, value) != true)) {
                    this.SENDING_STATUSField = value;
                    this.RaisePropertyChanged("SENDING_STATUS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<System.DateTime> UPD_DT {
            get {
                return this.UPD_DTField;
            }
            set {
                if ((this.UPD_DTField.Equals(value) != true)) {
                    this.UPD_DTField = value;
                    this.RaisePropertyChanged("UPD_DT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string ERR_CODE {
            get {
                return this.ERR_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.ERR_CODEField, value) != true)) {
                    this.ERR_CODEField = value;
                    this.RaisePropertyChanged("ERR_CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.Nullable<long> ZTB_SMS_TYPE_ID {
            get {
                return this.ZTB_SMS_TYPE_IDField;
            }
            set {
                if ((this.ZTB_SMS_TYPE_IDField.Equals(value) != true)) {
                    this.ZTB_SMS_TYPE_IDField = value;
                    this.RaisePropertyChanged("ZTB_SMS_TYPE_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string SENDER_NAME {
            get {
                return this.SENDER_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.SENDER_NAMEField, value) != true)) {
                    this.SENDER_NAMEField = value;
                    this.RaisePropertyChanged("SENDER_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.Nullable<long> APPLICATION_ID {
            get {
                return this.APPLICATION_IDField;
            }
            set {
                if ((this.APPLICATION_IDField.Equals(value) != true)) {
                    this.APPLICATION_IDField = value;
                    this.RaisePropertyChanged("APPLICATION_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string ERR_MESSAGE {
            get {
                return this.ERR_MESSAGEField;
            }
            set {
                if ((object.ReferenceEquals(this.ERR_MESSAGEField, value) != true)) {
                    this.ERR_MESSAGEField = value;
                    this.RaisePropertyChanged("ERR_MESSAGE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public NewBisPA.smsSvcRef.SMS_POLICY_SENDING SMS_POLICY_SENDING {
            get {
                return this.SMS_POLICY_SENDINGField;
            }
            set {
                if ((object.ReferenceEquals(this.SMS_POLICY_SENDINGField, value) != true)) {
                    this.SMS_POLICY_SENDINGField = value;
                    this.RaisePropertyChanged("SMS_POLICY_SENDING");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public NewBisPA.smsSvcRef.SMS_RECIPIENT_PERSON[] SMS_RECIPIENT_PERSON_Collection {
            get {
                return this.SMS_RECIPIENT_PERSON_CollectionField;
            }
            set {
                if ((object.ReferenceEquals(this.SMS_RECIPIENT_PERSON_CollectionField, value) != true)) {
                    this.SMS_RECIPIENT_PERSON_CollectionField = value;
                    this.RaisePropertyChanged("SMS_RECIPIENT_PERSON_Collection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public NewBisPA.smsSvcRef.SMS_REFERENCE[] SMS_REFERENCE_Collection {
            get {
                return this.SMS_REFERENCE_CollectionField;
            }
            set {
                if ((object.ReferenceEquals(this.SMS_REFERENCE_CollectionField, value) != true)) {
                    this.SMS_REFERENCE_CollectionField = value;
                    this.RaisePropertyChanged("SMS_REFERENCE_Collection");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SMS_POLICY_SENDING", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SMS_POLICY_SENDING : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<long> ZTB_SMS_IDField;
        
        private System.Nullable<long> POLICY_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JOB_CODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SUBJOB_CODEField;
        
        private System.Nullable<System.DateTime> DUE_DTField;
        
        private System.Nullable<int> POL_YRField;
        
        private System.Nullable<int> POL_LTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SEND_TYPEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SEND_CODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SMSTYPE_CODEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<long> ZTB_SMS_ID {
            get {
                return this.ZTB_SMS_IDField;
            }
            set {
                if ((this.ZTB_SMS_IDField.Equals(value) != true)) {
                    this.ZTB_SMS_IDField = value;
                    this.RaisePropertyChanged("ZTB_SMS_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.Nullable<long> POLICY_ID {
            get {
                return this.POLICY_IDField;
            }
            set {
                if ((this.POLICY_IDField.Equals(value) != true)) {
                    this.POLICY_IDField = value;
                    this.RaisePropertyChanged("POLICY_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string JOB_CODE {
            get {
                return this.JOB_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.JOB_CODEField, value) != true)) {
                    this.JOB_CODEField = value;
                    this.RaisePropertyChanged("JOB_CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string SUBJOB_CODE {
            get {
                return this.SUBJOB_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.SUBJOB_CODEField, value) != true)) {
                    this.SUBJOB_CODEField = value;
                    this.RaisePropertyChanged("SUBJOB_CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<System.DateTime> DUE_DT {
            get {
                return this.DUE_DTField;
            }
            set {
                if ((this.DUE_DTField.Equals(value) != true)) {
                    this.DUE_DTField = value;
                    this.RaisePropertyChanged("DUE_DT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<int> POL_YR {
            get {
                return this.POL_YRField;
            }
            set {
                if ((this.POL_YRField.Equals(value) != true)) {
                    this.POL_YRField = value;
                    this.RaisePropertyChanged("POL_YR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<int> POL_LT {
            get {
                return this.POL_LTField;
            }
            set {
                if ((this.POL_LTField.Equals(value) != true)) {
                    this.POL_LTField = value;
                    this.RaisePropertyChanged("POL_LT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string SEND_TYPE {
            get {
                return this.SEND_TYPEField;
            }
            set {
                if ((object.ReferenceEquals(this.SEND_TYPEField, value) != true)) {
                    this.SEND_TYPEField = value;
                    this.RaisePropertyChanged("SEND_TYPE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string SEND_CODE {
            get {
                return this.SEND_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.SEND_CODEField, value) != true)) {
                    this.SEND_CODEField = value;
                    this.RaisePropertyChanged("SEND_CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string SMSTYPE_CODE {
            get {
                return this.SMSTYPE_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.SMSTYPE_CODEField, value) != true)) {
                    this.SMSTYPE_CODEField = value;
                    this.RaisePropertyChanged("SMSTYPE_CODE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SMS_RECIPIENT_PERSON", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SMS_RECIPIENT_PERSON : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<long> ZTB_SMS_RECIPIENT_IDField;
        
        private System.Nullable<long> ZTB_SMS_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RECIPIENT_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MOBILE_NOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RECIPIENT_REFField;
        
        private System.Nullable<int> RECIPIENT_TYPEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SURNAMEField;
        
        private System.Nullable<System.DateTime> BIRTH_DTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDCARD_NOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DESCRIPTIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DATA_TYPEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string REF_TABLE_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string REF_COLUMN_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NewBisPA.smsSvcRef.ZTB_SMS_PERSON B_SMS_PERSONField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<long> ZTB_SMS_RECIPIENT_ID {
            get {
                return this.ZTB_SMS_RECIPIENT_IDField;
            }
            set {
                if ((this.ZTB_SMS_RECIPIENT_IDField.Equals(value) != true)) {
                    this.ZTB_SMS_RECIPIENT_IDField = value;
                    this.RaisePropertyChanged("ZTB_SMS_RECIPIENT_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.Nullable<long> ZTB_SMS_ID {
            get {
                return this.ZTB_SMS_IDField;
            }
            set {
                if ((this.ZTB_SMS_IDField.Equals(value) != true)) {
                    this.ZTB_SMS_IDField = value;
                    this.RaisePropertyChanged("ZTB_SMS_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string RECIPIENT_ID {
            get {
                return this.RECIPIENT_IDField;
            }
            set {
                if ((object.ReferenceEquals(this.RECIPIENT_IDField, value) != true)) {
                    this.RECIPIENT_IDField = value;
                    this.RaisePropertyChanged("RECIPIENT_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string MOBILE_NO {
            get {
                return this.MOBILE_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.MOBILE_NOField, value) != true)) {
                    this.MOBILE_NOField = value;
                    this.RaisePropertyChanged("MOBILE_NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string RECIPIENT_REF {
            get {
                return this.RECIPIENT_REFField;
            }
            set {
                if ((object.ReferenceEquals(this.RECIPIENT_REFField, value) != true)) {
                    this.RECIPIENT_REFField = value;
                    this.RaisePropertyChanged("RECIPIENT_REF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<int> RECIPIENT_TYPE {
            get {
                return this.RECIPIENT_TYPEField;
            }
            set {
                if ((this.RECIPIENT_TYPEField.Equals(value) != true)) {
                    this.RECIPIENT_TYPEField = value;
                    this.RaisePropertyChanged("RECIPIENT_TYPE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string NAME {
            get {
                return this.NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.NAMEField, value) != true)) {
                    this.NAMEField = value;
                    this.RaisePropertyChanged("NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string SURNAME {
            get {
                return this.SURNAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.SURNAMEField, value) != true)) {
                    this.SURNAMEField = value;
                    this.RaisePropertyChanged("SURNAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.Nullable<System.DateTime> BIRTH_DT {
            get {
                return this.BIRTH_DTField;
            }
            set {
                if ((this.BIRTH_DTField.Equals(value) != true)) {
                    this.BIRTH_DTField = value;
                    this.RaisePropertyChanged("BIRTH_DT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string IDCARD_NO {
            get {
                return this.IDCARD_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.IDCARD_NOField, value) != true)) {
                    this.IDCARD_NOField = value;
                    this.RaisePropertyChanged("IDCARD_NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string DESCRIPTION {
            get {
                return this.DESCRIPTIONField;
            }
            set {
                if ((object.ReferenceEquals(this.DESCRIPTIONField, value) != true)) {
                    this.DESCRIPTIONField = value;
                    this.RaisePropertyChanged("DESCRIPTION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string DATA_TYPE {
            get {
                return this.DATA_TYPEField;
            }
            set {
                if ((object.ReferenceEquals(this.DATA_TYPEField, value) != true)) {
                    this.DATA_TYPEField = value;
                    this.RaisePropertyChanged("DATA_TYPE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string REF_TABLE_NAME {
            get {
                return this.REF_TABLE_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.REF_TABLE_NAMEField, value) != true)) {
                    this.REF_TABLE_NAMEField = value;
                    this.RaisePropertyChanged("REF_TABLE_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string REF_COLUMN_NAME {
            get {
                return this.REF_COLUMN_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.REF_COLUMN_NAMEField, value) != true)) {
                    this.REF_COLUMN_NAMEField = value;
                    this.RaisePropertyChanged("REF_COLUMN_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public NewBisPA.smsSvcRef.ZTB_SMS_PERSON B_SMS_PERSON {
            get {
                return this.B_SMS_PERSONField;
            }
            set {
                if ((object.ReferenceEquals(this.B_SMS_PERSONField, value) != true)) {
                    this.B_SMS_PERSONField = value;
                    this.RaisePropertyChanged("B_SMS_PERSON");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SMS_REFERENCE", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NewBisPA.smsSvcRef.SMS_Get_Result))]
    public partial class SMS_REFERENCE : NewBisPA.smsSvcRef.ZTB_SMS_REFERENCE {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DESCRIPTIONField;
        
        private System.Nullable<char> DATA_TYPEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string REF_TABLE_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string REF_COLUMN_NAMEField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DESCRIPTION {
            get {
                return this.DESCRIPTIONField;
            }
            set {
                if ((object.ReferenceEquals(this.DESCRIPTIONField, value) != true)) {
                    this.DESCRIPTIONField = value;
                    this.RaisePropertyChanged("DESCRIPTION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.Nullable<char> DATA_TYPE {
            get {
                return this.DATA_TYPEField;
            }
            set {
                if ((this.DATA_TYPEField.Equals(value) != true)) {
                    this.DATA_TYPEField = value;
                    this.RaisePropertyChanged("DATA_TYPE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string REF_TABLE_NAME {
            get {
                return this.REF_TABLE_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.REF_TABLE_NAMEField, value) != true)) {
                    this.REF_TABLE_NAMEField = value;
                    this.RaisePropertyChanged("REF_TABLE_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string REF_COLUMN_NAME {
            get {
                return this.REF_COLUMN_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.REF_COLUMN_NAMEField, value) != true)) {
                    this.REF_COLUMN_NAMEField = value;
                    this.RaisePropertyChanged("REF_COLUMN_NAME");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ZTB_SMS_PERSON", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ZTB_SMS_PERSON : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<long> ZTB_SMS_RECIPIENT_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SURNAMEField;
        
        private System.Nullable<System.DateTime> BIRTH_DTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDCARD_NOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<long> ZTB_SMS_RECIPIENT_ID {
            get {
                return this.ZTB_SMS_RECIPIENT_IDField;
            }
            set {
                if ((this.ZTB_SMS_RECIPIENT_IDField.Equals(value) != true)) {
                    this.ZTB_SMS_RECIPIENT_IDField = value;
                    this.RaisePropertyChanged("ZTB_SMS_RECIPIENT_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string NAME {
            get {
                return this.NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.NAMEField, value) != true)) {
                    this.NAMEField = value;
                    this.RaisePropertyChanged("NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SURNAME {
            get {
                return this.SURNAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.SURNAMEField, value) != true)) {
                    this.SURNAMEField = value;
                    this.RaisePropertyChanged("SURNAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<System.DateTime> BIRTH_DT {
            get {
                return this.BIRTH_DTField;
            }
            set {
                if ((this.BIRTH_DTField.Equals(value) != true)) {
                    this.BIRTH_DTField = value;
                    this.RaisePropertyChanged("BIRTH_DT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string IDCARD_NO {
            get {
                return this.IDCARD_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.IDCARD_NOField, value) != true)) {
                    this.IDCARD_NOField = value;
                    this.RaisePropertyChanged("IDCARD_NO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ZTB_SMS_REFERENCE", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NewBisPA.smsSvcRef.SMS_REFERENCE))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NewBisPA.smsSvcRef.SMS_Get_Result))]
    public partial class ZTB_SMS_REFERENCE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<long> ZTB_SMS_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string REFERENCE_CODEField;
        
        private System.Nullable<int> REFERENCE_TYPEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<long> ZTB_SMS_ID {
            get {
                return this.ZTB_SMS_IDField;
            }
            set {
                if ((this.ZTB_SMS_IDField.Equals(value) != true)) {
                    this.ZTB_SMS_IDField = value;
                    this.RaisePropertyChanged("ZTB_SMS_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string REFERENCE_CODE {
            get {
                return this.REFERENCE_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.REFERENCE_CODEField, value) != true)) {
                    this.REFERENCE_CODEField = value;
                    this.RaisePropertyChanged("REFERENCE_CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<int> REFERENCE_TYPE {
            get {
                return this.REFERENCE_TYPEField;
            }
            set {
                if ((this.REFERENCE_TYPEField.Equals(value) != true)) {
                    this.REFERENCE_TYPEField = value;
                    this.RaisePropertyChanged("REFERENCE_TYPE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SMS_Get_Result", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SMS_Get_Result : NewBisPA.smsSvcRef.SMS_REFERENCE {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubJobField;
        
        private System.Nullable<long> PolicyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PolicyNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CertificateNoField;
        
        private System.Nullable<System.DateTime> StartDateField;
        
        private System.Nullable<System.DateTime> EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Sender {
            get {
                return this.SenderField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderField, value) != true)) {
                    this.SenderField = value;
                    this.RaisePropertyChanged("Sender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Job {
            get {
                return this.JobField;
            }
            set {
                if ((object.ReferenceEquals(this.JobField, value) != true)) {
                    this.JobField = value;
                    this.RaisePropertyChanged("Job");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SubJob {
            get {
                return this.SubJobField;
            }
            set {
                if ((object.ReferenceEquals(this.SubJobField, value) != true)) {
                    this.SubJobField = value;
                    this.RaisePropertyChanged("SubJob");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<long> PolicyID {
            get {
                return this.PolicyIDField;
            }
            set {
                if ((this.PolicyIDField.Equals(value) != true)) {
                    this.PolicyIDField = value;
                    this.RaisePropertyChanged("PolicyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string PolicyNo {
            get {
                return this.PolicyNoField;
            }
            set {
                if ((object.ReferenceEquals(this.PolicyNoField, value) != true)) {
                    this.PolicyNoField = value;
                    this.RaisePropertyChanged("PolicyNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string CertificateNo {
            get {
                return this.CertificateNoField;
            }
            set {
                if ((object.ReferenceEquals(this.CertificateNoField, value) != true)) {
                    this.CertificateNoField = value;
                    this.RaisePropertyChanged("CertificateNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<System.DateTime> StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<System.DateTime> EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string PhoneNo {
            get {
                return this.PhoneNoField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNoField, value) != true)) {
                    this.PhoneNoField = value;
                    this.RaisePropertyChanged("PhoneNo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ProcessResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool SuccessedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Successed {
            get {
                return this.SuccessedField;
            }
            set {
                if ((this.SuccessedField.Equals(value) != true)) {
                    this.SuccessedField = value;
                    this.RaisePropertyChanged("Successed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SMS_Send_Result", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SMS_Send_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderField;
        
        private System.Nullable<long> PolicyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PolicyNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CertNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NewBisPA.smsSvcRef.SMS_RECIPIENT_PERSON[] SMS_RECIPIENT_PERSON_CollectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SendStatusField;
        
        private System.Nullable<System.DateTime> SendDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubJobField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Job_DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubJob_DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NewBisPA.smsSvcRef.ZTB_SMS_ERROR ZTB_SMS_ERRORField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NewBisPA.smsSvcRef.SMS_REFERENCE SMS_REFERENCEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SMS_TYPE_CODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SMS_TYPE_DESCRIPTIONField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Sender {
            get {
                return this.SenderField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderField, value) != true)) {
                    this.SenderField = value;
                    this.RaisePropertyChanged("Sender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<long> PolicyID {
            get {
                return this.PolicyIDField;
            }
            set {
                if ((this.PolicyIDField.Equals(value) != true)) {
                    this.PolicyIDField = value;
                    this.RaisePropertyChanged("PolicyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PolicyNo {
            get {
                return this.PolicyNoField;
            }
            set {
                if ((object.ReferenceEquals(this.PolicyNoField, value) != true)) {
                    this.PolicyNoField = value;
                    this.RaisePropertyChanged("PolicyNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CertNo {
            get {
                return this.CertNoField;
            }
            set {
                if ((object.ReferenceEquals(this.CertNoField, value) != true)) {
                    this.CertNoField = value;
                    this.RaisePropertyChanged("CertNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public NewBisPA.smsSvcRef.SMS_RECIPIENT_PERSON[] SMS_RECIPIENT_PERSON_Collection {
            get {
                return this.SMS_RECIPIENT_PERSON_CollectionField;
            }
            set {
                if ((object.ReferenceEquals(this.SMS_RECIPIENT_PERSON_CollectionField, value) != true)) {
                    this.SMS_RECIPIENT_PERSON_CollectionField = value;
                    this.RaisePropertyChanged("SMS_RECIPIENT_PERSON_Collection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string SendStatus {
            get {
                return this.SendStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.SendStatusField, value) != true)) {
                    this.SendStatusField = value;
                    this.RaisePropertyChanged("SendStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<System.DateTime> SendDate {
            get {
                return this.SendDateField;
            }
            set {
                if ((this.SendDateField.Equals(value) != true)) {
                    this.SendDateField = value;
                    this.RaisePropertyChanged("SendDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Job {
            get {
                return this.JobField;
            }
            set {
                if ((object.ReferenceEquals(this.JobField, value) != true)) {
                    this.JobField = value;
                    this.RaisePropertyChanged("Job");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string SubJob {
            get {
                return this.SubJobField;
            }
            set {
                if ((object.ReferenceEquals(this.SubJobField, value) != true)) {
                    this.SubJobField = value;
                    this.RaisePropertyChanged("SubJob");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Job_Description {
            get {
                return this.Job_DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.Job_DescriptionField, value) != true)) {
                    this.Job_DescriptionField = value;
                    this.RaisePropertyChanged("Job_Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string SubJob_Description {
            get {
                return this.SubJob_DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.SubJob_DescriptionField, value) != true)) {
                    this.SubJob_DescriptionField = value;
                    this.RaisePropertyChanged("SubJob_Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public NewBisPA.smsSvcRef.ZTB_SMS_ERROR ZTB_SMS_ERROR {
            get {
                return this.ZTB_SMS_ERRORField;
            }
            set {
                if ((object.ReferenceEquals(this.ZTB_SMS_ERRORField, value) != true)) {
                    this.ZTB_SMS_ERRORField = value;
                    this.RaisePropertyChanged("ZTB_SMS_ERROR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public NewBisPA.smsSvcRef.SMS_REFERENCE SMS_REFERENCE {
            get {
                return this.SMS_REFERENCEField;
            }
            set {
                if ((object.ReferenceEquals(this.SMS_REFERENCEField, value) != true)) {
                    this.SMS_REFERENCEField = value;
                    this.RaisePropertyChanged("SMS_REFERENCE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string SMS_TYPE_CODE {
            get {
                return this.SMS_TYPE_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.SMS_TYPE_CODEField, value) != true)) {
                    this.SMS_TYPE_CODEField = value;
                    this.RaisePropertyChanged("SMS_TYPE_CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string SMS_TYPE_DESCRIPTION {
            get {
                return this.SMS_TYPE_DESCRIPTIONField;
            }
            set {
                if ((object.ReferenceEquals(this.SMS_TYPE_DESCRIPTIONField, value) != true)) {
                    this.SMS_TYPE_DESCRIPTIONField = value;
                    this.RaisePropertyChanged("SMS_TYPE_DESCRIPTION");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ZTB_SMS_ERROR", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ZTB_SMS_ERROR : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<char> ERR_CODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ERR_DESCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ERR_DESC_THField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NewBisPA.smsSvcRef.ZTB_SMS[] B_SMS_CollectionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<char> ERR_CODE {
            get {
                return this.ERR_CODEField;
            }
            set {
                if ((this.ERR_CODEField.Equals(value) != true)) {
                    this.ERR_CODEField = value;
                    this.RaisePropertyChanged("ERR_CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ERR_DESC {
            get {
                return this.ERR_DESCField;
            }
            set {
                if ((object.ReferenceEquals(this.ERR_DESCField, value) != true)) {
                    this.ERR_DESCField = value;
                    this.RaisePropertyChanged("ERR_DESC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ERR_DESC_TH {
            get {
                return this.ERR_DESC_THField;
            }
            set {
                if ((object.ReferenceEquals(this.ERR_DESC_THField, value) != true)) {
                    this.ERR_DESC_THField = value;
                    this.RaisePropertyChanged("ERR_DESC_TH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public NewBisPA.smsSvcRef.ZTB_SMS[] B_SMS_Collection {
            get {
                return this.B_SMS_CollectionField;
            }
            set {
                if ((object.ReferenceEquals(this.B_SMS_CollectionField, value) != true)) {
                    this.B_SMS_CollectionField = value;
                    this.RaisePropertyChanged("B_SMS_Collection");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ZTB_SMS", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ZTB_SMS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<long> ZTB_SMS_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MESSAGEField;
        
        private System.Nullable<long> ZTB_ORG_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OFFICEField;
        
        private System.Nullable<System.DateTime> SEND_DTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SEND_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SENDING_STATUSField;
        
        private System.Nullable<System.DateTime> UPD_DTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ERR_CODEField;
        
        private System.Nullable<long> ZTB_SMS_TYPE_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SENDER_NAMEField;
        
        private System.Nullable<long> APPLICATION_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NewBisPA.smsSvcRef.ZTB_SMS_POLICY B_SMS_POLICYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NewBisPA.smsSvcRef.ZTB_SMS_RECIPIENT[] B_SMS_RECIPIENT_CollectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NewBisPA.smsSvcRef.ZTB_SMS_REFERENCE B_SMS_REFERENCEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<long> ZTB_SMS_ID {
            get {
                return this.ZTB_SMS_IDField;
            }
            set {
                if ((this.ZTB_SMS_IDField.Equals(value) != true)) {
                    this.ZTB_SMS_IDField = value;
                    this.RaisePropertyChanged("ZTB_SMS_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MESSAGE {
            get {
                return this.MESSAGEField;
            }
            set {
                if ((object.ReferenceEquals(this.MESSAGEField, value) != true)) {
                    this.MESSAGEField = value;
                    this.RaisePropertyChanged("MESSAGE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<long> ZTB_ORG_ID {
            get {
                return this.ZTB_ORG_IDField;
            }
            set {
                if ((this.ZTB_ORG_IDField.Equals(value) != true)) {
                    this.ZTB_ORG_IDField = value;
                    this.RaisePropertyChanged("ZTB_ORG_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string OFFICE {
            get {
                return this.OFFICEField;
            }
            set {
                if ((object.ReferenceEquals(this.OFFICEField, value) != true)) {
                    this.OFFICEField = value;
                    this.RaisePropertyChanged("OFFICE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<System.DateTime> SEND_DT {
            get {
                return this.SEND_DTField;
            }
            set {
                if ((this.SEND_DTField.Equals(value) != true)) {
                    this.SEND_DTField = value;
                    this.RaisePropertyChanged("SEND_DT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string SEND_ID {
            get {
                return this.SEND_IDField;
            }
            set {
                if ((object.ReferenceEquals(this.SEND_IDField, value) != true)) {
                    this.SEND_IDField = value;
                    this.RaisePropertyChanged("SEND_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string SENDING_STATUS {
            get {
                return this.SENDING_STATUSField;
            }
            set {
                if ((object.ReferenceEquals(this.SENDING_STATUSField, value) != true)) {
                    this.SENDING_STATUSField = value;
                    this.RaisePropertyChanged("SENDING_STATUS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<System.DateTime> UPD_DT {
            get {
                return this.UPD_DTField;
            }
            set {
                if ((this.UPD_DTField.Equals(value) != true)) {
                    this.UPD_DTField = value;
                    this.RaisePropertyChanged("UPD_DT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string ERR_CODE {
            get {
                return this.ERR_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.ERR_CODEField, value) != true)) {
                    this.ERR_CODEField = value;
                    this.RaisePropertyChanged("ERR_CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.Nullable<long> ZTB_SMS_TYPE_ID {
            get {
                return this.ZTB_SMS_TYPE_IDField;
            }
            set {
                if ((this.ZTB_SMS_TYPE_IDField.Equals(value) != true)) {
                    this.ZTB_SMS_TYPE_IDField = value;
                    this.RaisePropertyChanged("ZTB_SMS_TYPE_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string SENDER_NAME {
            get {
                return this.SENDER_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.SENDER_NAMEField, value) != true)) {
                    this.SENDER_NAMEField = value;
                    this.RaisePropertyChanged("SENDER_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.Nullable<long> APPLICATION_ID {
            get {
                return this.APPLICATION_IDField;
            }
            set {
                if ((this.APPLICATION_IDField.Equals(value) != true)) {
                    this.APPLICATION_IDField = value;
                    this.RaisePropertyChanged("APPLICATION_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public NewBisPA.smsSvcRef.ZTB_SMS_POLICY B_SMS_POLICY {
            get {
                return this.B_SMS_POLICYField;
            }
            set {
                if ((object.ReferenceEquals(this.B_SMS_POLICYField, value) != true)) {
                    this.B_SMS_POLICYField = value;
                    this.RaisePropertyChanged("B_SMS_POLICY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public NewBisPA.smsSvcRef.ZTB_SMS_RECIPIENT[] B_SMS_RECIPIENT_Collection {
            get {
                return this.B_SMS_RECIPIENT_CollectionField;
            }
            set {
                if ((object.ReferenceEquals(this.B_SMS_RECIPIENT_CollectionField, value) != true)) {
                    this.B_SMS_RECIPIENT_CollectionField = value;
                    this.RaisePropertyChanged("B_SMS_RECIPIENT_Collection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public NewBisPA.smsSvcRef.ZTB_SMS_REFERENCE B_SMS_REFERENCE {
            get {
                return this.B_SMS_REFERENCEField;
            }
            set {
                if ((object.ReferenceEquals(this.B_SMS_REFERENCEField, value) != true)) {
                    this.B_SMS_REFERENCEField = value;
                    this.RaisePropertyChanged("B_SMS_REFERENCE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ZTB_SMS_POLICY", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ZTB_SMS_POLICY : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<long> ZTB_SMS_IDField;
        
        private System.Nullable<long> POLICY_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JOB_CODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SUBJOB_CODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JOB_DESCRIPTIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SUBJOB_DESCRIPTIONField;
        
        private System.Nullable<System.DateTime> DUE_DTField;
        
        private System.Nullable<int> POL_YRField;
        
        private System.Nullable<int> POL_LTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SEND_TYPEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SEND_CODEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<long> ZTB_SMS_ID {
            get {
                return this.ZTB_SMS_IDField;
            }
            set {
                if ((this.ZTB_SMS_IDField.Equals(value) != true)) {
                    this.ZTB_SMS_IDField = value;
                    this.RaisePropertyChanged("ZTB_SMS_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.Nullable<long> POLICY_ID {
            get {
                return this.POLICY_IDField;
            }
            set {
                if ((this.POLICY_IDField.Equals(value) != true)) {
                    this.POLICY_IDField = value;
                    this.RaisePropertyChanged("POLICY_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string JOB_CODE {
            get {
                return this.JOB_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.JOB_CODEField, value) != true)) {
                    this.JOB_CODEField = value;
                    this.RaisePropertyChanged("JOB_CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string SUBJOB_CODE {
            get {
                return this.SUBJOB_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.SUBJOB_CODEField, value) != true)) {
                    this.SUBJOB_CODEField = value;
                    this.RaisePropertyChanged("SUBJOB_CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string JOB_DESCRIPTION {
            get {
                return this.JOB_DESCRIPTIONField;
            }
            set {
                if ((object.ReferenceEquals(this.JOB_DESCRIPTIONField, value) != true)) {
                    this.JOB_DESCRIPTIONField = value;
                    this.RaisePropertyChanged("JOB_DESCRIPTION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string SUBJOB_DESCRIPTION {
            get {
                return this.SUBJOB_DESCRIPTIONField;
            }
            set {
                if ((object.ReferenceEquals(this.SUBJOB_DESCRIPTIONField, value) != true)) {
                    this.SUBJOB_DESCRIPTIONField = value;
                    this.RaisePropertyChanged("SUBJOB_DESCRIPTION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<System.DateTime> DUE_DT {
            get {
                return this.DUE_DTField;
            }
            set {
                if ((this.DUE_DTField.Equals(value) != true)) {
                    this.DUE_DTField = value;
                    this.RaisePropertyChanged("DUE_DT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<int> POL_YR {
            get {
                return this.POL_YRField;
            }
            set {
                if ((this.POL_YRField.Equals(value) != true)) {
                    this.POL_YRField = value;
                    this.RaisePropertyChanged("POL_YR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.Nullable<int> POL_LT {
            get {
                return this.POL_LTField;
            }
            set {
                if ((this.POL_LTField.Equals(value) != true)) {
                    this.POL_LTField = value;
                    this.RaisePropertyChanged("POL_LT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string SEND_TYPE {
            get {
                return this.SEND_TYPEField;
            }
            set {
                if ((object.ReferenceEquals(this.SEND_TYPEField, value) != true)) {
                    this.SEND_TYPEField = value;
                    this.RaisePropertyChanged("SEND_TYPE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string SEND_CODE {
            get {
                return this.SEND_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.SEND_CODEField, value) != true)) {
                    this.SEND_CODEField = value;
                    this.RaisePropertyChanged("SEND_CODE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ZTB_SMS_RECIPIENT", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ZTB_SMS_RECIPIENT : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<long> ZTB_SMS_RECIPIENT_IDField;
        
        private System.Nullable<long> ZTB_SMS_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RECIPIENT_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MOBILE_NOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RECIPIENT_REFField;
        
        private System.Nullable<int> RECIPIENT_TYPEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NewBisPA.smsSvcRef.ZTB_SMS_PERSON B_SMS_PERSONField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<long> ZTB_SMS_RECIPIENT_ID {
            get {
                return this.ZTB_SMS_RECIPIENT_IDField;
            }
            set {
                if ((this.ZTB_SMS_RECIPIENT_IDField.Equals(value) != true)) {
                    this.ZTB_SMS_RECIPIENT_IDField = value;
                    this.RaisePropertyChanged("ZTB_SMS_RECIPIENT_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.Nullable<long> ZTB_SMS_ID {
            get {
                return this.ZTB_SMS_IDField;
            }
            set {
                if ((this.ZTB_SMS_IDField.Equals(value) != true)) {
                    this.ZTB_SMS_IDField = value;
                    this.RaisePropertyChanged("ZTB_SMS_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string RECIPIENT_ID {
            get {
                return this.RECIPIENT_IDField;
            }
            set {
                if ((object.ReferenceEquals(this.RECIPIENT_IDField, value) != true)) {
                    this.RECIPIENT_IDField = value;
                    this.RaisePropertyChanged("RECIPIENT_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string MOBILE_NO {
            get {
                return this.MOBILE_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.MOBILE_NOField, value) != true)) {
                    this.MOBILE_NOField = value;
                    this.RaisePropertyChanged("MOBILE_NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string RECIPIENT_REF {
            get {
                return this.RECIPIENT_REFField;
            }
            set {
                if ((object.ReferenceEquals(this.RECIPIENT_REFField, value) != true)) {
                    this.RECIPIENT_REFField = value;
                    this.RaisePropertyChanged("RECIPIENT_REF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<int> RECIPIENT_TYPE {
            get {
                return this.RECIPIENT_TYPEField;
            }
            set {
                if ((this.RECIPIENT_TYPEField.Equals(value) != true)) {
                    this.RECIPIENT_TYPEField = value;
                    this.RaisePropertyChanged("RECIPIENT_TYPE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public NewBisPA.smsSvcRef.ZTB_SMS_PERSON B_SMS_PERSON {
            get {
                return this.B_SMS_PERSONField;
            }
            set {
                if ((object.ReferenceEquals(this.B_SMS_PERSONField, value) != true)) {
                    this.B_SMS_PERSONField = value;
                    this.RaisePropertyChanged("B_SMS_PERSON");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="smsSvcRef.Sms_SvcSoap")]
    public interface Sms_SvcSoap {
        
        // CODEGEN: Generating message contract since element name param from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMS", ReplyAction="*")]
        NewBisPA.smsSvcRef.SendSMSResponse SendSMS(NewBisPA.smsSvcRef.SendSMSRequest request);
        
        // CODEGEN: Generating message contract since element name get from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSMS_Send_Result", ReplyAction="*")]
        NewBisPA.smsSvcRef.GetSMS_Send_ResultResponse GetSMS_Send_Result(NewBisPA.smsSvcRef.GetSMS_Send_ResultRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMS", Namespace="http://tempuri.org/", Order=0)]
        public NewBisPA.smsSvcRef.SendSMSRequestBody Body;
        
        public SendSMSRequest() {
        }
        
        public SendSMSRequest(NewBisPA.smsSvcRef.SendSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NewBisPA.smsSvcRef.Param_SMS param;
        
        public SendSMSRequestBody() {
        }
        
        public SendSMSRequestBody(NewBisPA.smsSvcRef.Param_SMS param) {
            this.param = param;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSResponse", Namespace="http://tempuri.org/", Order=0)]
        public NewBisPA.smsSvcRef.SendSMSResponseBody Body;
        
        public SendSMSResponse() {
        }
        
        public SendSMSResponse(NewBisPA.smsSvcRef.SendSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NewBisPA.smsSvcRef.ProcessResult SendSMSResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public NewBisPA.smsSvcRef.Param_SMS param;
        
        public SendSMSResponseBody() {
        }
        
        public SendSMSResponseBody(NewBisPA.smsSvcRef.ProcessResult SendSMSResult, NewBisPA.smsSvcRef.Param_SMS param) {
            this.SendSMSResult = SendSMSResult;
            this.param = param;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSMS_Send_ResultRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSMS_Send_Result", Namespace="http://tempuri.org/", Order=0)]
        public NewBisPA.smsSvcRef.GetSMS_Send_ResultRequestBody Body;
        
        public GetSMS_Send_ResultRequest() {
        }
        
        public GetSMS_Send_ResultRequest(NewBisPA.smsSvcRef.GetSMS_Send_ResultRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSMS_Send_ResultRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NewBisPA.smsSvcRef.SMS_Get_Result get;
        
        public GetSMS_Send_ResultRequestBody() {
        }
        
        public GetSMS_Send_ResultRequestBody(NewBisPA.smsSvcRef.SMS_Get_Result get) {
            this.get = get;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSMS_Send_ResultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSMS_Send_ResultResponse", Namespace="http://tempuri.org/", Order=0)]
        public NewBisPA.smsSvcRef.GetSMS_Send_ResultResponseBody Body;
        
        public GetSMS_Send_ResultResponse() {
        }
        
        public GetSMS_Send_ResultResponse(NewBisPA.smsSvcRef.GetSMS_Send_ResultResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSMS_Send_ResultResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NewBisPA.smsSvcRef.SMS_Send_Result[] GetSMS_Send_ResultResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public NewBisPA.smsSvcRef.ProcessResult pr;
        
        public GetSMS_Send_ResultResponseBody() {
        }
        
        public GetSMS_Send_ResultResponseBody(NewBisPA.smsSvcRef.SMS_Send_Result[] GetSMS_Send_ResultResult, NewBisPA.smsSvcRef.ProcessResult pr) {
            this.GetSMS_Send_ResultResult = GetSMS_Send_ResultResult;
            this.pr = pr;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Sms_SvcSoapChannel : NewBisPA.smsSvcRef.Sms_SvcSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Sms_SvcSoapClient : System.ServiceModel.ClientBase<NewBisPA.smsSvcRef.Sms_SvcSoap>, NewBisPA.smsSvcRef.Sms_SvcSoap {
        
        public Sms_SvcSoapClient() {
        }
        
        public Sms_SvcSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Sms_SvcSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Sms_SvcSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Sms_SvcSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NewBisPA.smsSvcRef.SendSMSResponse NewBisPA.smsSvcRef.Sms_SvcSoap.SendSMS(NewBisPA.smsSvcRef.SendSMSRequest request) {
            return base.Channel.SendSMS(request);
        }
        
        public NewBisPA.smsSvcRef.ProcessResult SendSMS(ref NewBisPA.smsSvcRef.Param_SMS param) {
            NewBisPA.smsSvcRef.SendSMSRequest inValue = new NewBisPA.smsSvcRef.SendSMSRequest();
            inValue.Body = new NewBisPA.smsSvcRef.SendSMSRequestBody();
            inValue.Body.param = param;
            NewBisPA.smsSvcRef.SendSMSResponse retVal = ((NewBisPA.smsSvcRef.Sms_SvcSoap)(this)).SendSMS(inValue);
            param = retVal.Body.param;
            return retVal.Body.SendSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NewBisPA.smsSvcRef.GetSMS_Send_ResultResponse NewBisPA.smsSvcRef.Sms_SvcSoap.GetSMS_Send_Result(NewBisPA.smsSvcRef.GetSMS_Send_ResultRequest request) {
            return base.Channel.GetSMS_Send_Result(request);
        }
        
        public NewBisPA.smsSvcRef.SMS_Send_Result[] GetSMS_Send_Result(NewBisPA.smsSvcRef.SMS_Get_Result get, out NewBisPA.smsSvcRef.ProcessResult pr) {
            NewBisPA.smsSvcRef.GetSMS_Send_ResultRequest inValue = new NewBisPA.smsSvcRef.GetSMS_Send_ResultRequest();
            inValue.Body = new NewBisPA.smsSvcRef.GetSMS_Send_ResultRequestBody();
            inValue.Body.get = get;
            NewBisPA.smsSvcRef.GetSMS_Send_ResultResponse retVal = ((NewBisPA.smsSvcRef.Sms_SvcSoap)(this)).GetSMS_Send_Result(inValue);
            pr = retVal.Body.pr;
            return retVal.Body.GetSMS_Send_ResultResult;
        }
    }
}
