//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewBisPA.BankruptSvcRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bankrupt", Namespace="http://BankruptServices.Model/2011/BankruptServiceModel")]
    [System.SerializableAttribute()]
    public partial class Bankrupt : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SysIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime JudgmentDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedNoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NewBisPA.BankruptSvcRef.BankruptStatus BankruptStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegisterCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RegisterTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime KeyCreatedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyCreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyCreatedNoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NewBisPA.BankruptSvcRef.BankruptLogCollection BankruptLogCollectionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SysID {
            get {
                return this.SysIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SysIDField, value) != true)) {
                    this.SysIDField = value;
                    this.RaisePropertyChanged("SysID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime JudgmentDate {
            get {
                return this.JudgmentDateField;
            }
            set {
                if ((this.JudgmentDateField.Equals(value) != true)) {
                    this.JudgmentDateField = value;
                    this.RaisePropertyChanged("JudgmentDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime CreatedOn {
            get {
                return this.CreatedOnField;
            }
            set {
                if ((this.CreatedOnField.Equals(value) != true)) {
                    this.CreatedOnField = value;
                    this.RaisePropertyChanged("CreatedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string CreatedNote {
            get {
                return this.CreatedNoteField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedNoteField, value) != true)) {
                    this.CreatedNoteField = value;
                    this.RaisePropertyChanged("CreatedNote");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public NewBisPA.BankruptSvcRef.BankruptStatus BankruptStatus {
            get {
                return this.BankruptStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.BankruptStatusField, value) != true)) {
                    this.BankruptStatusField = value;
                    this.RaisePropertyChanged("BankruptStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string RegisterCode {
            get {
                return this.RegisterCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.RegisterCodeField, value) != true)) {
                    this.RegisterCodeField = value;
                    this.RaisePropertyChanged("RegisterCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int RegisterType {
            get {
                return this.RegisterTypeField;
            }
            set {
                if ((this.RegisterTypeField.Equals(value) != true)) {
                    this.RegisterTypeField = value;
                    this.RaisePropertyChanged("RegisterType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public System.DateTime KeyCreatedOn {
            get {
                return this.KeyCreatedOnField;
            }
            set {
                if ((this.KeyCreatedOnField.Equals(value) != true)) {
                    this.KeyCreatedOnField = value;
                    this.RaisePropertyChanged("KeyCreatedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string KeyCreatedBy {
            get {
                return this.KeyCreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyCreatedByField, value) != true)) {
                    this.KeyCreatedByField = value;
                    this.RaisePropertyChanged("KeyCreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string KeyCreatedNote {
            get {
                return this.KeyCreatedNoteField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyCreatedNoteField, value) != true)) {
                    this.KeyCreatedNoteField = value;
                    this.RaisePropertyChanged("KeyCreatedNote");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public NewBisPA.BankruptSvcRef.BankruptLogCollection BankruptLogCollection {
            get {
                return this.BankruptLogCollectionField;
            }
            set {
                if ((object.ReferenceEquals(this.BankruptLogCollectionField, value) != true)) {
                    this.BankruptLogCollectionField = value;
                    this.RaisePropertyChanged("BankruptLogCollection");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankruptStatus", Namespace="http://BankruptServices.Model/2011/BankruptServiceModel")]
    [System.SerializableAttribute()]
    public partial class BankruptStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatusCode {
            get {
                return this.StatusCodeField;
            }
            set {
                if ((this.StatusCodeField.Equals(value) != true)) {
                    this.StatusCodeField = value;
                    this.RaisePropertyChanged("StatusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Detail {
            get {
                return this.DetailField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailField, value) != true)) {
                    this.DetailField = value;
                    this.RaisePropertyChanged("Detail");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="BankruptLogCollection", Namespace="http://BankruptServices.Model/2011/BankruptServiceModel", ItemName="BankruptLog")]
    [System.SerializableAttribute()]
    public class BankruptLogCollection : System.Collections.Generic.List<NewBisPA.BankruptSvcRef.BankruptLog> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankruptLog", Namespace="http://BankruptServices.Model/2011/BankruptServiceModel")]
    [System.SerializableAttribute()]
    public partial class BankruptLog : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TxnIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SysIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime JudgmentDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedNoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NewBisPA.BankruptSvcRef.BankruptStatus BankruptStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TxnID {
            get {
                return this.TxnIDField;
            }
            set {
                if ((object.ReferenceEquals(this.TxnIDField, value) != true)) {
                    this.TxnIDField = value;
                    this.RaisePropertyChanged("TxnID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string SysID {
            get {
                return this.SysIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SysIDField, value) != true)) {
                    this.SysIDField = value;
                    this.RaisePropertyChanged("SysID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime JudgmentDate {
            get {
                return this.JudgmentDateField;
            }
            set {
                if ((this.JudgmentDateField.Equals(value) != true)) {
                    this.JudgmentDateField = value;
                    this.RaisePropertyChanged("JudgmentDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime CreatedOn {
            get {
                return this.CreatedOnField;
            }
            set {
                if ((this.CreatedOnField.Equals(value) != true)) {
                    this.CreatedOnField = value;
                    this.RaisePropertyChanged("CreatedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string CreatedNote {
            get {
                return this.CreatedNoteField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedNoteField, value) != true)) {
                    this.CreatedNoteField = value;
                    this.RaisePropertyChanged("CreatedNote");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public NewBisPA.BankruptSvcRef.BankruptStatus BankruptStatus {
            get {
                return this.BankruptStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.BankruptStatusField, value) != true)) {
                    this.BankruptStatusField = value;
                    this.RaisePropertyChanged("BankruptStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="BankruptCollection", Namespace="http://BankruptServices.Model/2011/BankruptServiceModel", ItemName="Bankrupt")]
    [System.SerializableAttribute()]
    public class BankruptCollection : System.Collections.Generic.List<NewBisPA.BankruptSvcRef.Bankrupt> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://BankruptServices.Model/2011/BankruptServiceModel", ConfigurationName="BankruptSvcRef.BankruptServiceContract")]
    public interface BankruptServiceContract {
        
        // CODEGEN: Generating message contract since the wrapper name (NewBankruptRequest) of message NewBankruptRequest does not match the default value (NewBankrupt)
        [System.ServiceModel.OperationContractAttribute(Action="http://BankruptServices.Model/2011/BankruptServiceModel/BankruptServiceContract/N" +
            "ewBankrupt", ReplyAction="http://BankruptServices.Model/2011/BankruptServiceModel/BankruptServiceContract/N" +
            "ewBankruptResponse")]
        NewBisPA.BankruptSvcRef.NewBankruptResponse NewBankrupt(NewBisPA.BankruptSvcRef.NewBankruptRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (UpdateBankruptRequest) of message UpdateBankruptRequest does not match the default value (UpdateBankrupt)
        [System.ServiceModel.OperationContractAttribute(Action="http://BankruptServices.Model/2011/BankruptServiceModel/BankruptServiceContract/U" +
            "pdateBankrupt", ReplyAction="http://BankruptServices.Model/2011/BankruptServiceModel/BankruptServiceContract/U" +
            "pdateBankruptResponse")]
        NewBisPA.BankruptSvcRef.UpdateBankruptResponse UpdateBankrupt(NewBisPA.BankruptSvcRef.UpdateBankruptRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (GetBankruptByRegIDRequest) of message GetBankruptByRegIDRequest does not match the default value (GetBankruptByRegID)
        [System.ServiceModel.OperationContractAttribute(Action="http://BankruptServices.Model/2011/BankruptServiceModel/BankruptServiceContract/G" +
            "etBankruptByRegID", ReplyAction="http://BankruptServices.Model/2011/BankruptServiceModel/BankruptServiceContract/G" +
            "etBankruptByRegIDResponse")]
        NewBisPA.BankruptSvcRef.GetBankruptByRegIDResponse GetBankruptByRegID(NewBisPA.BankruptSvcRef.GetBankruptByRegIDRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (LoadBankruptByNameRequest) of message LoadBankruptByNameRequest does not match the default value (LoadBankruptByName)
        [System.ServiceModel.OperationContractAttribute(Action="http://BankruptServices.Model/2011/BankruptServiceModel/BankruptServiceContract/L" +
            "oadBankruptByName", ReplyAction="http://BankruptServices.Model/2011/BankruptServiceModel/BankruptServiceContract/L" +
            "oadBankruptByNameResponse")]
        NewBisPA.BankruptSvcRef.LoadBankruptByNameResponse LoadBankruptByName(NewBisPA.BankruptSvcRef.LoadBankruptByNameRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (LoadBankruptLogBySysIDRequest) of message LoadBankruptLogBySysIDRequest does not match the default value (LoadBankruptLogBySysID)
        [System.ServiceModel.OperationContractAttribute(Action="http://BankruptServices.Model/2011/BankruptServiceModel/BankruptServiceContract/L" +
            "oadBankruptLogBySysID", ReplyAction="http://BankruptServices.Model/2011/BankruptServiceModel/BankruptServiceContract/L" +
            "oadBankruptLogBySysIDResponse")]
        NewBisPA.BankruptSvcRef.LoadBankruptLogBySysIDResponse LoadBankruptLogBySysID(NewBisPA.BankruptSvcRef.LoadBankruptLogBySysIDRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (GetSysIDByRegIDRequest) of message GetSysIDByRegIDRequest does not match the default value (GetSysIDByRegID)
        [System.ServiceModel.OperationContractAttribute(Action="http://BankruptServices.Model/2011/BankruptServiceModel/BankruptServiceContract/G" +
            "etSysIDByRegID", ReplyAction="http://BankruptServices.Model/2011/BankruptServiceModel/BankruptServiceContract/G" +
            "etSysIDByRegIDResponse")]
        NewBisPA.BankruptSvcRef.GetSysIDByRegIDResponse GetSysIDByRegID(NewBisPA.BankruptSvcRef.GetSysIDByRegIDRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (LoadBankruptLogByNameRequest) of message LoadBankruptLogByNameRequest does not match the default value (LoadBankruptLogByName)
        [System.ServiceModel.OperationContractAttribute(Action="http://BankruptServices.Model/2011/BankruptServiceModel/BankruptServiceContract/L" +
            "oadBankruptLogByName", ReplyAction="http://BankruptServices.Model/2011/BankruptServiceModel/BankruptServiceContract/L" +
            "oadBankruptLogByNameResponse")]
        NewBisPA.BankruptSvcRef.LoadBankruptLogByNameResponse LoadBankruptLogByName(NewBisPA.BankruptSvcRef.LoadBankruptLogByNameRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (LoadBankruptLogByRegIDRequest) of message LoadBankruptLogByRegIDRequest does not match the default value (LoadBankruptLogByRegID)
        [System.ServiceModel.OperationContractAttribute(Action="http://BankruptServices.Model/2011/BankruptServiceModel/BankruptServiceContract/L" +
            "oadBankruptLogByRegID", ReplyAction="http://BankruptServices.Model/2011/BankruptServiceModel/BankruptServiceContract/L" +
            "oadBankruptLogByRegIDResponse")]
        NewBisPA.BankruptSvcRef.LoadBankruptLogByRegIDResponse LoadBankruptLogByRegID(NewBisPA.BankruptSvcRef.LoadBankruptLogByRegIDRequest request);
        
        // CODEGEN: Generating message contract since the operation EditBankrupt is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://BankruptServices.Model/2011/BankruptServiceModel/BankruptServiceContract/E" +
            "ditBankrupt", ReplyAction="http://BankruptServices.Model/2011/BankruptServiceModel/BankruptServiceContract/E" +
            "ditBankruptResponse")]
        NewBisPA.BankruptSvcRef.EditBankruptResponse EditBankrupt(NewBisPA.BankruptSvcRef.EditBankruptRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (LoadBankruptRequest) of message LoadBankruptRequest does not match the default value (LoadBankrupt)
        [System.ServiceModel.OperationContractAttribute(Action="http://BankruptServices.Model/2011/BankruptServiceModel/BankruptServiceContract/L" +
            "oadBankrupt", ReplyAction="http://BankruptServices.Model/2011/BankruptServiceModel/BankruptServiceContract/L" +
            "oadBankruptResponse")]
        NewBisPA.BankruptSvcRef.LoadBankruptResponse LoadBankrupt(NewBisPA.BankruptSvcRef.LoadBankruptRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (GetBankruptRequest) of message GetBankruptRequest does not match the default value (GetBankrupt)
        [System.ServiceModel.OperationContractAttribute(Action="http://BankruptServices.Model/2011/BankruptServiceModel/BankruptServiceContract/G" +
            "etBankrupt", ReplyAction="http://BankruptServices.Model/2011/BankruptServiceModel/BankruptServiceContract/G" +
            "etBankruptResponse")]
        NewBisPA.BankruptSvcRef.GetBankruptResponse GetBankrupt(NewBisPA.BankruptSvcRef.GetBankruptRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NewBankruptRequest", WrapperNamespace="http://BankruptServices.Model/2011/BankruptServiceModel", IsWrapped=true)]
    public partial class NewBankruptRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BankruptServices.Model/2011/BankruptServiceModel", Order=0)]
        public NewBisPA.BankruptSvcRef.Bankrupt Bankrupt;
        
        public NewBankruptRequest() {
        }
        
        public NewBankruptRequest(NewBisPA.BankruptSvcRef.Bankrupt Bankrupt) {
            this.Bankrupt = Bankrupt;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NewBankruptResponse", WrapperNamespace="http://BankruptServices.Model/2011/BankruptServiceModel", IsWrapped=true)]
    public partial class NewBankruptResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BankruptServices.Model/2011/BankruptServiceModel", Order=0)]
        public System.DateTime CreatedOn;
        
        public NewBankruptResponse() {
        }
        
        public NewBankruptResponse(System.DateTime CreatedOn) {
            this.CreatedOn = CreatedOn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateBankruptRequest", WrapperNamespace="http://BankruptServices.Model/2011/BankruptServiceModel", IsWrapped=true)]
    public partial class UpdateBankruptRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BankruptServices.Model/2011/BankruptServiceModel", Order=0)]
        public NewBisPA.BankruptSvcRef.Bankrupt Bankrupt;
        
        public UpdateBankruptRequest() {
        }
        
        public UpdateBankruptRequest(NewBisPA.BankruptSvcRef.Bankrupt Bankrupt) {
            this.Bankrupt = Bankrupt;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateBankruptResponse", WrapperNamespace="http://BankruptServices.Model/2011/BankruptServiceModel", IsWrapped=true)]
    public partial class UpdateBankruptResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BankruptServices.Model/2011/BankruptServiceModel", Order=0)]
        public System.DateTime ModifiedOn;
        
        public UpdateBankruptResponse() {
        }
        
        public UpdateBankruptResponse(System.DateTime ModifiedOn) {
            this.ModifiedOn = ModifiedOn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBankruptByRegIDRequest", WrapperNamespace="http://BankruptServices.Model/2011/BankruptServiceModel", IsWrapped=true)]
    public partial class GetBankruptByRegIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BankruptServices.Model/2011/BankruptServiceModel", Order=0)]
        public string RegisterCode;
        
        public GetBankruptByRegIDRequest() {
        }
        
        public GetBankruptByRegIDRequest(string RegisterCode) {
            this.RegisterCode = RegisterCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBankruptByRegIDResponse", WrapperNamespace="http://BankruptServices.Model/2011/BankruptServiceModel", IsWrapped=true)]
    public partial class GetBankruptByRegIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BankruptServices.Model/2011/BankruptServiceModel", Order=0)]
        public NewBisPA.BankruptSvcRef.Bankrupt Bankrupt;
        
        public GetBankruptByRegIDResponse() {
        }
        
        public GetBankruptByRegIDResponse(NewBisPA.BankruptSvcRef.Bankrupt Bankrupt) {
            this.Bankrupt = Bankrupt;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadBankruptByNameRequest", WrapperNamespace="http://BankruptServices.Model/2011/BankruptServiceModel", IsWrapped=true)]
    public partial class LoadBankruptByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BankruptServices.Model/2011/BankruptServiceModel", Order=0)]
        public string SearchLname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BankruptServices.Model/2011/BankruptServiceModel", Order=1)]
        public string SearchName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BankruptServices.Model/2011/BankruptServiceModel", Order=2)]
        public int SearchType;
        
        public LoadBankruptByNameRequest() {
        }
        
        public LoadBankruptByNameRequest(string SearchLname, string SearchName, int SearchType) {
            this.SearchLname = SearchLname;
            this.SearchName = SearchName;
            this.SearchType = SearchType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadBankruptByNameResponse", WrapperNamespace="http://BankruptServices.Model/2011/BankruptServiceModel", IsWrapped=true)]
    public partial class LoadBankruptByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BankruptServices.Model/2011/BankruptServiceModel", Order=0)]
        public NewBisPA.BankruptSvcRef.BankruptCollection BankruptCollection;
        
        public LoadBankruptByNameResponse() {
        }
        
        public LoadBankruptByNameResponse(NewBisPA.BankruptSvcRef.BankruptCollection BankruptCollection) {
            this.BankruptCollection = BankruptCollection;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadBankruptLogBySysIDRequest", WrapperNamespace="http://BankruptServices.Model/2011/BankruptServiceModel", IsWrapped=true)]
    public partial class LoadBankruptLogBySysIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BankruptServices.Model/2011/BankruptServiceModel", Order=0)]
        public string SysID;
        
        public LoadBankruptLogBySysIDRequest() {
        }
        
        public LoadBankruptLogBySysIDRequest(string SysID) {
            this.SysID = SysID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadBankruptLogBySysIDResponse", WrapperNamespace="http://BankruptServices.Model/2011/BankruptServiceModel", IsWrapped=true)]
    public partial class LoadBankruptLogBySysIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BankruptServices.Model/2011/BankruptServiceModel", Order=0)]
        public NewBisPA.BankruptSvcRef.BankruptLogCollection BankruptLogCollection;
        
        public LoadBankruptLogBySysIDResponse() {
        }
        
        public LoadBankruptLogBySysIDResponse(NewBisPA.BankruptSvcRef.BankruptLogCollection BankruptLogCollection) {
            this.BankruptLogCollection = BankruptLogCollection;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSysIDByRegIDRequest", WrapperNamespace="http://BankruptServices.Model/2011/BankruptServiceModel", IsWrapped=true)]
    public partial class GetSysIDByRegIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BankruptServices.Model/2011/BankruptServiceModel", Order=0)]
        public string RegisterCode;
        
        public GetSysIDByRegIDRequest() {
        }
        
        public GetSysIDByRegIDRequest(string RegisterCode) {
            this.RegisterCode = RegisterCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSysIDByRegIDResponse", WrapperNamespace="http://BankruptServices.Model/2011/BankruptServiceModel", IsWrapped=true)]
    public partial class GetSysIDByRegIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BankruptServices.Model/2011/BankruptServiceModel", Order=0)]
        public string SysID;
        
        public GetSysIDByRegIDResponse() {
        }
        
        public GetSysIDByRegIDResponse(string SysID) {
            this.SysID = SysID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadBankruptLogByNameRequest", WrapperNamespace="http://BankruptServices.Model/2011/BankruptServiceModel", IsWrapped=true)]
    public partial class LoadBankruptLogByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BankruptServices.Model/2011/BankruptServiceModel", Order=0)]
        public string SearchLname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BankruptServices.Model/2011/BankruptServiceModel", Order=1)]
        public string SearchName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BankruptServices.Model/2011/BankruptServiceModel", Order=2)]
        public int SearchType;
        
        public LoadBankruptLogByNameRequest() {
        }
        
        public LoadBankruptLogByNameRequest(string SearchLname, string SearchName, int SearchType) {
            this.SearchLname = SearchLname;
            this.SearchName = SearchName;
            this.SearchType = SearchType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadBankruptLogByNameResponse", WrapperNamespace="http://BankruptServices.Model/2011/BankruptServiceModel", IsWrapped=true)]
    public partial class LoadBankruptLogByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BankruptServices.Model/2011/BankruptServiceModel", Order=0)]
        public NewBisPA.BankruptSvcRef.BankruptCollection BankruptCollection;
        
        public LoadBankruptLogByNameResponse() {
        }
        
        public LoadBankruptLogByNameResponse(NewBisPA.BankruptSvcRef.BankruptCollection BankruptCollection) {
            this.BankruptCollection = BankruptCollection;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadBankruptLogByRegIDRequest", WrapperNamespace="http://BankruptServices.Model/2011/BankruptServiceModel", IsWrapped=true)]
    public partial class LoadBankruptLogByRegIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BankruptServices.Model/2011/BankruptServiceModel", Order=0)]
        public string SearchRegisterCode;
        
        public LoadBankruptLogByRegIDRequest() {
        }
        
        public LoadBankruptLogByRegIDRequest(string SearchRegisterCode) {
            this.SearchRegisterCode = SearchRegisterCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadBankruptLogByRegIDResponse", WrapperNamespace="http://BankruptServices.Model/2011/BankruptServiceModel", IsWrapped=true)]
    public partial class LoadBankruptLogByRegIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BankruptServices.Model/2011/BankruptServiceModel", Order=0)]
        public NewBisPA.BankruptSvcRef.BankruptCollection BankruptCollection;
        
        public LoadBankruptLogByRegIDResponse() {
        }
        
        public LoadBankruptLogByRegIDResponse(NewBisPA.BankruptSvcRef.BankruptCollection BankruptCollection) {
            this.BankruptCollection = BankruptCollection;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditBankruptRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BankruptServices.Model/2011/BankruptServiceModel", Order=0)]
        public NewBisPA.BankruptSvcRef.Bankrupt Bankrupt;
        
        public EditBankruptRequest() {
        }
        
        public EditBankruptRequest(NewBisPA.BankruptSvcRef.Bankrupt Bankrupt) {
            this.Bankrupt = Bankrupt;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditBankruptResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BankruptServices.Model/2011/BankruptServiceModel", Order=0)]
        public System.DateTime ModifiedOn;
        
        public EditBankruptResponse() {
        }
        
        public EditBankruptResponse(System.DateTime ModifiedOn) {
            this.ModifiedOn = ModifiedOn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadBankruptRequest", WrapperNamespace="http://BankruptServices.Model/2011/BankruptServiceModel", IsWrapped=true)]
    public partial class LoadBankruptRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BankruptServices.Model/2011/BankruptServiceModel", Order=0)]
        public string IDNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BankruptServices.Model/2011/BankruptServiceModel", Order=1)]
        public string FirstName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BankruptServices.Model/2011/BankruptServiceModel", Order=2)]
        public string LastName;
        
        public LoadBankruptRequest() {
        }
        
        public LoadBankruptRequest(string IDNumber, string FirstName, string LastName) {
            this.IDNumber = IDNumber;
            this.FirstName = FirstName;
            this.LastName = LastName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadBankruptResponse", WrapperNamespace="http://BankruptServices.Model/2011/BankruptServiceModel", IsWrapped=true)]
    public partial class LoadBankruptResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BankruptServices.Model/2011/BankruptServiceModel", Order=0)]
        public NewBisPA.BankruptSvcRef.BankruptCollection BankruptCollection;
        
        public LoadBankruptResponse() {
        }
        
        public LoadBankruptResponse(NewBisPA.BankruptSvcRef.BankruptCollection BankruptCollection) {
            this.BankruptCollection = BankruptCollection;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBankruptRequest", WrapperNamespace="http://BankruptServices.Model/2011/BankruptServiceModel", IsWrapped=true)]
    public partial class GetBankruptRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BankruptServices.Model/2011/BankruptServiceModel", Order=0)]
        public string IDNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BankruptServices.Model/2011/BankruptServiceModel", Order=1)]
        public string FirstName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BankruptServices.Model/2011/BankruptServiceModel", Order=2)]
        public string LastName;
        
        public GetBankruptRequest() {
        }
        
        public GetBankruptRequest(string IDNumber, string FirstName, string LastName) {
            this.IDNumber = IDNumber;
            this.FirstName = FirstName;
            this.LastName = LastName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBankruptResponse", WrapperNamespace="http://BankruptServices.Model/2011/BankruptServiceModel", IsWrapped=true)]
    public partial class GetBankruptResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BankruptServices.Model/2011/BankruptServiceModel", Order=0)]
        public NewBisPA.BankruptSvcRef.Bankrupt Bankrupt;
        
        public GetBankruptResponse() {
        }
        
        public GetBankruptResponse(NewBisPA.BankruptSvcRef.Bankrupt Bankrupt) {
            this.Bankrupt = Bankrupt;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BankruptServiceContractChannel : NewBisPA.BankruptSvcRef.BankruptServiceContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BankruptServiceContractClient : System.ServiceModel.ClientBase<NewBisPA.BankruptSvcRef.BankruptServiceContract>, NewBisPA.BankruptSvcRef.BankruptServiceContract {
        
        public BankruptServiceContractClient() {
        }
        
        public BankruptServiceContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BankruptServiceContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankruptServiceContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankruptServiceContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NewBisPA.BankruptSvcRef.NewBankruptResponse NewBisPA.BankruptSvcRef.BankruptServiceContract.NewBankrupt(NewBisPA.BankruptSvcRef.NewBankruptRequest request) {
            return base.Channel.NewBankrupt(request);
        }
        
        public System.DateTime NewBankrupt(NewBisPA.BankruptSvcRef.Bankrupt Bankrupt) {
            NewBisPA.BankruptSvcRef.NewBankruptRequest inValue = new NewBisPA.BankruptSvcRef.NewBankruptRequest();
            inValue.Bankrupt = Bankrupt;
            NewBisPA.BankruptSvcRef.NewBankruptResponse retVal = ((NewBisPA.BankruptSvcRef.BankruptServiceContract)(this)).NewBankrupt(inValue);
            return retVal.CreatedOn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NewBisPA.BankruptSvcRef.UpdateBankruptResponse NewBisPA.BankruptSvcRef.BankruptServiceContract.UpdateBankrupt(NewBisPA.BankruptSvcRef.UpdateBankruptRequest request) {
            return base.Channel.UpdateBankrupt(request);
        }
        
        public System.DateTime UpdateBankrupt(NewBisPA.BankruptSvcRef.Bankrupt Bankrupt) {
            NewBisPA.BankruptSvcRef.UpdateBankruptRequest inValue = new NewBisPA.BankruptSvcRef.UpdateBankruptRequest();
            inValue.Bankrupt = Bankrupt;
            NewBisPA.BankruptSvcRef.UpdateBankruptResponse retVal = ((NewBisPA.BankruptSvcRef.BankruptServiceContract)(this)).UpdateBankrupt(inValue);
            return retVal.ModifiedOn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NewBisPA.BankruptSvcRef.GetBankruptByRegIDResponse NewBisPA.BankruptSvcRef.BankruptServiceContract.GetBankruptByRegID(NewBisPA.BankruptSvcRef.GetBankruptByRegIDRequest request) {
            return base.Channel.GetBankruptByRegID(request);
        }
        
        public NewBisPA.BankruptSvcRef.Bankrupt GetBankruptByRegID(string RegisterCode) {
            NewBisPA.BankruptSvcRef.GetBankruptByRegIDRequest inValue = new NewBisPA.BankruptSvcRef.GetBankruptByRegIDRequest();
            inValue.RegisterCode = RegisterCode;
            NewBisPA.BankruptSvcRef.GetBankruptByRegIDResponse retVal = ((NewBisPA.BankruptSvcRef.BankruptServiceContract)(this)).GetBankruptByRegID(inValue);
            return retVal.Bankrupt;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NewBisPA.BankruptSvcRef.LoadBankruptByNameResponse NewBisPA.BankruptSvcRef.BankruptServiceContract.LoadBankruptByName(NewBisPA.BankruptSvcRef.LoadBankruptByNameRequest request) {
            return base.Channel.LoadBankruptByName(request);
        }
        
        public NewBisPA.BankruptSvcRef.BankruptCollection LoadBankruptByName(string SearchLname, string SearchName, int SearchType) {
            NewBisPA.BankruptSvcRef.LoadBankruptByNameRequest inValue = new NewBisPA.BankruptSvcRef.LoadBankruptByNameRequest();
            inValue.SearchLname = SearchLname;
            inValue.SearchName = SearchName;
            inValue.SearchType = SearchType;
            NewBisPA.BankruptSvcRef.LoadBankruptByNameResponse retVal = ((NewBisPA.BankruptSvcRef.BankruptServiceContract)(this)).LoadBankruptByName(inValue);
            return retVal.BankruptCollection;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NewBisPA.BankruptSvcRef.LoadBankruptLogBySysIDResponse NewBisPA.BankruptSvcRef.BankruptServiceContract.LoadBankruptLogBySysID(NewBisPA.BankruptSvcRef.LoadBankruptLogBySysIDRequest request) {
            return base.Channel.LoadBankruptLogBySysID(request);
        }
        
        public NewBisPA.BankruptSvcRef.BankruptLogCollection LoadBankruptLogBySysID(string SysID) {
            NewBisPA.BankruptSvcRef.LoadBankruptLogBySysIDRequest inValue = new NewBisPA.BankruptSvcRef.LoadBankruptLogBySysIDRequest();
            inValue.SysID = SysID;
            NewBisPA.BankruptSvcRef.LoadBankruptLogBySysIDResponse retVal = ((NewBisPA.BankruptSvcRef.BankruptServiceContract)(this)).LoadBankruptLogBySysID(inValue);
            return retVal.BankruptLogCollection;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NewBisPA.BankruptSvcRef.GetSysIDByRegIDResponse NewBisPA.BankruptSvcRef.BankruptServiceContract.GetSysIDByRegID(NewBisPA.BankruptSvcRef.GetSysIDByRegIDRequest request) {
            return base.Channel.GetSysIDByRegID(request);
        }
        
        public string GetSysIDByRegID(string RegisterCode) {
            NewBisPA.BankruptSvcRef.GetSysIDByRegIDRequest inValue = new NewBisPA.BankruptSvcRef.GetSysIDByRegIDRequest();
            inValue.RegisterCode = RegisterCode;
            NewBisPA.BankruptSvcRef.GetSysIDByRegIDResponse retVal = ((NewBisPA.BankruptSvcRef.BankruptServiceContract)(this)).GetSysIDByRegID(inValue);
            return retVal.SysID;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NewBisPA.BankruptSvcRef.LoadBankruptLogByNameResponse NewBisPA.BankruptSvcRef.BankruptServiceContract.LoadBankruptLogByName(NewBisPA.BankruptSvcRef.LoadBankruptLogByNameRequest request) {
            return base.Channel.LoadBankruptLogByName(request);
        }
        
        public NewBisPA.BankruptSvcRef.BankruptCollection LoadBankruptLogByName(string SearchLname, string SearchName, int SearchType) {
            NewBisPA.BankruptSvcRef.LoadBankruptLogByNameRequest inValue = new NewBisPA.BankruptSvcRef.LoadBankruptLogByNameRequest();
            inValue.SearchLname = SearchLname;
            inValue.SearchName = SearchName;
            inValue.SearchType = SearchType;
            NewBisPA.BankruptSvcRef.LoadBankruptLogByNameResponse retVal = ((NewBisPA.BankruptSvcRef.BankruptServiceContract)(this)).LoadBankruptLogByName(inValue);
            return retVal.BankruptCollection;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NewBisPA.BankruptSvcRef.LoadBankruptLogByRegIDResponse NewBisPA.BankruptSvcRef.BankruptServiceContract.LoadBankruptLogByRegID(NewBisPA.BankruptSvcRef.LoadBankruptLogByRegIDRequest request) {
            return base.Channel.LoadBankruptLogByRegID(request);
        }
        
        public NewBisPA.BankruptSvcRef.BankruptCollection LoadBankruptLogByRegID(string SearchRegisterCode) {
            NewBisPA.BankruptSvcRef.LoadBankruptLogByRegIDRequest inValue = new NewBisPA.BankruptSvcRef.LoadBankruptLogByRegIDRequest();
            inValue.SearchRegisterCode = SearchRegisterCode;
            NewBisPA.BankruptSvcRef.LoadBankruptLogByRegIDResponse retVal = ((NewBisPA.BankruptSvcRef.BankruptServiceContract)(this)).LoadBankruptLogByRegID(inValue);
            return retVal.BankruptCollection;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NewBisPA.BankruptSvcRef.EditBankruptResponse NewBisPA.BankruptSvcRef.BankruptServiceContract.EditBankrupt(NewBisPA.BankruptSvcRef.EditBankruptRequest request) {
            return base.Channel.EditBankrupt(request);
        }
        
        public System.DateTime EditBankrupt(NewBisPA.BankruptSvcRef.Bankrupt Bankrupt) {
            NewBisPA.BankruptSvcRef.EditBankruptRequest inValue = new NewBisPA.BankruptSvcRef.EditBankruptRequest();
            inValue.Bankrupt = Bankrupt;
            NewBisPA.BankruptSvcRef.EditBankruptResponse retVal = ((NewBisPA.BankruptSvcRef.BankruptServiceContract)(this)).EditBankrupt(inValue);
            return retVal.ModifiedOn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NewBisPA.BankruptSvcRef.LoadBankruptResponse NewBisPA.BankruptSvcRef.BankruptServiceContract.LoadBankrupt(NewBisPA.BankruptSvcRef.LoadBankruptRequest request) {
            return base.Channel.LoadBankrupt(request);
        }
        
        public NewBisPA.BankruptSvcRef.BankruptCollection LoadBankrupt(string IDNumber, string FirstName, string LastName) {
            NewBisPA.BankruptSvcRef.LoadBankruptRequest inValue = new NewBisPA.BankruptSvcRef.LoadBankruptRequest();
            inValue.IDNumber = IDNumber;
            inValue.FirstName = FirstName;
            inValue.LastName = LastName;
            NewBisPA.BankruptSvcRef.LoadBankruptResponse retVal = ((NewBisPA.BankruptSvcRef.BankruptServiceContract)(this)).LoadBankrupt(inValue);
            return retVal.BankruptCollection;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NewBisPA.BankruptSvcRef.GetBankruptResponse NewBisPA.BankruptSvcRef.BankruptServiceContract.GetBankrupt(NewBisPA.BankruptSvcRef.GetBankruptRequest request) {
            return base.Channel.GetBankrupt(request);
        }
        
        public NewBisPA.BankruptSvcRef.Bankrupt GetBankrupt(string IDNumber, string FirstName, string LastName) {
            NewBisPA.BankruptSvcRef.GetBankruptRequest inValue = new NewBisPA.BankruptSvcRef.GetBankruptRequest();
            inValue.IDNumber = IDNumber;
            inValue.FirstName = FirstName;
            inValue.LastName = LastName;
            NewBisPA.BankruptSvcRef.GetBankruptResponse retVal = ((NewBisPA.BankruptSvcRef.BankruptServiceContract)(this)).GetBankrupt(inValue);
            return retVal.Bankrupt;
        }
    }
}
