//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewBisPA.IsisAppTransportService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrdBilling", Namespace="http://schemas.datacontract.org/2004/07/AppTransport.DataContract", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class OrdBilling : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgentCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AmphurField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long BillIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NewBisPA.IsisAppTransportService.OrdBillingDue[] BillingDuesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NewBisPA.IsisAppTransportService.OrdBillingPayBy BillingPayByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CertificateNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDCardNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime InstallDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime IssueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MoohField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NeedToRearrangeContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PassportNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PayModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PolicyDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PolicyNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PreNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TambolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressName {
            get {
                return this.AddressNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressNameField, value) != true)) {
                    this.AddressNameField = value;
                    this.RaisePropertyChanged("AddressName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressNumber {
            get {
                return this.AddressNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressNumberField, value) != true)) {
                    this.AddressNumberField = value;
                    this.RaisePropertyChanged("AddressNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgentCode {
            get {
                return this.AgentCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AgentCodeField, value) != true)) {
                    this.AgentCodeField = value;
                    this.RaisePropertyChanged("AgentCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Amphur {
            get {
                return this.AmphurField;
            }
            set {
                if ((object.ReferenceEquals(this.AmphurField, value) != true)) {
                    this.AmphurField = value;
                    this.RaisePropertyChanged("Amphur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long BillID {
            get {
                return this.BillIDField;
            }
            set {
                if ((this.BillIDField.Equals(value) != true)) {
                    this.BillIDField = value;
                    this.RaisePropertyChanged("BillID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NewBisPA.IsisAppTransportService.OrdBillingDue[] BillingDues {
            get {
                return this.BillingDuesField;
            }
            set {
                if ((object.ReferenceEquals(this.BillingDuesField, value) != true)) {
                    this.BillingDuesField = value;
                    this.RaisePropertyChanged("BillingDues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NewBisPA.IsisAppTransportService.OrdBillingPayBy BillingPayBy {
            get {
                return this.BillingPayByField;
            }
            set {
                if ((object.ReferenceEquals(this.BillingPayByField, value) != true)) {
                    this.BillingPayByField = value;
                    this.RaisePropertyChanged("BillingPayBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CertificateNumber {
            get {
                return this.CertificateNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CertificateNumberField, value) != true)) {
                    this.CertificateNumberField = value;
                    this.RaisePropertyChanged("CertificateNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDCardNumber {
            get {
                return this.IDCardNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.IDCardNumberField, value) != true)) {
                    this.IDCardNumberField = value;
                    this.RaisePropertyChanged("IDCardNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InstallDate {
            get {
                return this.InstallDateField;
            }
            set {
                if ((this.InstallDateField.Equals(value) != true)) {
                    this.InstallDateField = value;
                    this.RaisePropertyChanged("InstallDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime IssueDate {
            get {
                return this.IssueDateField;
            }
            set {
                if ((this.IssueDateField.Equals(value) != true)) {
                    this.IssueDateField = value;
                    this.RaisePropertyChanged("IssueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mooh {
            get {
                return this.MoohField;
            }
            set {
                if ((object.ReferenceEquals(this.MoohField, value) != true)) {
                    this.MoohField = value;
                    this.RaisePropertyChanged("Mooh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NeedToRearrangeContent {
            get {
                return this.NeedToRearrangeContentField;
            }
            set {
                if ((this.NeedToRearrangeContentField.Equals(value) != true)) {
                    this.NeedToRearrangeContentField = value;
                    this.RaisePropertyChanged("NeedToRearrangeContent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PassportNumber {
            get {
                return this.PassportNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PassportNumberField, value) != true)) {
                    this.PassportNumberField = value;
                    this.RaisePropertyChanged("PassportNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PayMode {
            get {
                return this.PayModeField;
            }
            set {
                if ((this.PayModeField.Equals(value) != true)) {
                    this.PayModeField = value;
                    this.RaisePropertyChanged("PayMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PolicyDate {
            get {
                return this.PolicyDateField;
            }
            set {
                if ((this.PolicyDateField.Equals(value) != true)) {
                    this.PolicyDateField = value;
                    this.RaisePropertyChanged("PolicyDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PolicyNumber {
            get {
                return this.PolicyNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PolicyNumberField, value) != true)) {
                    this.PolicyNumberField = value;
                    this.RaisePropertyChanged("PolicyNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreName {
            get {
                return this.PreNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PreNameField, value) != true)) {
                    this.PreNameField = value;
                    this.RaisePropertyChanged("PreName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Province {
            get {
                return this.ProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinceField, value) != true)) {
                    this.ProvinceField = value;
                    this.RaisePropertyChanged("Province");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Road {
            get {
                return this.RoadField;
            }
            set {
                if ((object.ReferenceEquals(this.RoadField, value) != true)) {
                    this.RoadField = value;
                    this.RaisePropertyChanged("Road");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Soi {
            get {
                return this.SoiField;
            }
            set {
                if ((object.ReferenceEquals(this.SoiField, value) != true)) {
                    this.SoiField = value;
                    this.RaisePropertyChanged("Soi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tambol {
            get {
                return this.TambolField;
            }
            set {
                if ((object.ReferenceEquals(this.TambolField, value) != true)) {
                    this.TambolField = value;
                    this.RaisePropertyChanged("Tambol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIDField, value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipCodeField, value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrdBillingPayBy", Namespace="http://schemas.datacontract.org/2004/07/AppTransport.DataContract", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class OrdBillingPayBy : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDCardNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PassportNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PreNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDCardNumber {
            get {
                return this.IDCardNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.IDCardNumberField, value) != true)) {
                    this.IDCardNumberField = value;
                    this.RaisePropertyChanged("IDCardNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PassportNumber {
            get {
                return this.PassportNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PassportNumberField, value) != true)) {
                    this.PassportNumberField = value;
                    this.RaisePropertyChanged("PassportNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreName {
            get {
                return this.PreNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PreNameField, value) != true)) {
                    this.PreNameField = value;
                    this.RaisePropertyChanged("PreName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrdBillingDue", Namespace="http://schemas.datacontract.org/2004/07/AppTransport.DataContract", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class OrdBillingDue : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BillDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long BillDueIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NewBisPA.IsisAppTransportService.OrdBillingCancel BillingCancelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NewBisPA.IsisAppTransportService.OrdBillingPlan[] BillingPlansField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillingRemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PolicyLotField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PolicyYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PremiumTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TaxRemarkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BillDate {
            get {
                return this.BillDateField;
            }
            set {
                if ((this.BillDateField.Equals(value) != true)) {
                    this.BillDateField = value;
                    this.RaisePropertyChanged("BillDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long BillDueID {
            get {
                return this.BillDueIDField;
            }
            set {
                if ((this.BillDueIDField.Equals(value) != true)) {
                    this.BillDueIDField = value;
                    this.RaisePropertyChanged("BillDueID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillNumber {
            get {
                return this.BillNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.BillNumberField, value) != true)) {
                    this.BillNumberField = value;
                    this.RaisePropertyChanged("BillNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NewBisPA.IsisAppTransportService.OrdBillingCancel BillingCancel {
            get {
                return this.BillingCancelField;
            }
            set {
                if ((object.ReferenceEquals(this.BillingCancelField, value) != true)) {
                    this.BillingCancelField = value;
                    this.RaisePropertyChanged("BillingCancel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NewBisPA.IsisAppTransportService.OrdBillingPlan[] BillingPlans {
            get {
                return this.BillingPlansField;
            }
            set {
                if ((object.ReferenceEquals(this.BillingPlansField, value) != true)) {
                    this.BillingPlansField = value;
                    this.RaisePropertyChanged("BillingPlans");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillingRemark {
            get {
                return this.BillingRemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.BillingRemarkField, value) != true)) {
                    this.BillingRemarkField = value;
                    this.RaisePropertyChanged("BillingRemark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DueDate {
            get {
                return this.DueDateField;
            }
            set {
                if ((this.DueDateField.Equals(value) != true)) {
                    this.DueDateField = value;
                    this.RaisePropertyChanged("DueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PolicyLot {
            get {
                return this.PolicyLotField;
            }
            set {
                if ((this.PolicyLotField.Equals(value) != true)) {
                    this.PolicyLotField = value;
                    this.RaisePropertyChanged("PolicyLot");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PolicyYear {
            get {
                return this.PolicyYearField;
            }
            set {
                if ((this.PolicyYearField.Equals(value) != true)) {
                    this.PolicyYearField = value;
                    this.RaisePropertyChanged("PolicyYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PremiumType {
            get {
                return this.PremiumTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.PremiumTypeField, value) != true)) {
                    this.PremiumTypeField = value;
                    this.RaisePropertyChanged("PremiumType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaxRemark {
            get {
                return this.TaxRemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.TaxRemarkField, value) != true)) {
                    this.TaxRemarkField = value;
                    this.RaisePropertyChanged("TaxRemark");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrdBillingCancel", Namespace="http://schemas.datacontract.org/2004/07/AppTransport.DataContract", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class OrdBillingCancel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CancelTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillNumber {
            get {
                return this.BillNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.BillNumberField, value) != true)) {
                    this.BillNumberField = value;
                    this.RaisePropertyChanged("BillNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CancelType {
            get {
                return this.CancelTypeField;
            }
            set {
                if ((this.CancelTypeField.Equals(value) != true)) {
                    this.CancelTypeField = value;
                    this.RaisePropertyChanged("CancelType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReasonCode {
            get {
                return this.ReasonCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonCodeField, value) != true)) {
                    this.ReasonCodeField = value;
                    this.RaisePropertyChanged("ReasonCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIDField, value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrdBillingPlan", Namespace="http://schemas.datacontract.org/2004/07/AppTransport.DataContract", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class OrdBillingPlan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AssureYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long BillPlanIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal EFPremiumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal EMPremiumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PayYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlanBlockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlanCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlanCode2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlanTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PremiumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SummField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TaxPremiumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal XOCPPremiumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal XTRPremiumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AssureYear {
            get {
                return this.AssureYearField;
            }
            set {
                if ((this.AssureYearField.Equals(value) != true)) {
                    this.AssureYearField = value;
                    this.RaisePropertyChanged("AssureYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long BillPlanID {
            get {
                return this.BillPlanIDField;
            }
            set {
                if ((this.BillPlanIDField.Equals(value) != true)) {
                    this.BillPlanIDField = value;
                    this.RaisePropertyChanged("BillPlanID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal EFPremium {
            get {
                return this.EFPremiumField;
            }
            set {
                if ((this.EFPremiumField.Equals(value) != true)) {
                    this.EFPremiumField = value;
                    this.RaisePropertyChanged("EFPremium");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal EMPremium {
            get {
                return this.EMPremiumField;
            }
            set {
                if ((this.EMPremiumField.Equals(value) != true)) {
                    this.EMPremiumField = value;
                    this.RaisePropertyChanged("EMPremium");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PayYear {
            get {
                return this.PayYearField;
            }
            set {
                if ((this.PayYearField.Equals(value) != true)) {
                    this.PayYearField = value;
                    this.RaisePropertyChanged("PayYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlanBlock {
            get {
                return this.PlanBlockField;
            }
            set {
                if ((object.ReferenceEquals(this.PlanBlockField, value) != true)) {
                    this.PlanBlockField = value;
                    this.RaisePropertyChanged("PlanBlock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlanCode {
            get {
                return this.PlanCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PlanCodeField, value) != true)) {
                    this.PlanCodeField = value;
                    this.RaisePropertyChanged("PlanCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlanCode2 {
            get {
                return this.PlanCode2Field;
            }
            set {
                if ((object.ReferenceEquals(this.PlanCode2Field, value) != true)) {
                    this.PlanCode2Field = value;
                    this.RaisePropertyChanged("PlanCode2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlanType {
            get {
                return this.PlanTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.PlanTypeField, value) != true)) {
                    this.PlanTypeField = value;
                    this.RaisePropertyChanged("PlanType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Premium {
            get {
                return this.PremiumField;
            }
            set {
                if ((this.PremiumField.Equals(value) != true)) {
                    this.PremiumField = value;
                    this.RaisePropertyChanged("Premium");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Summ {
            get {
                return this.SummField;
            }
            set {
                if ((this.SummField.Equals(value) != true)) {
                    this.SummField = value;
                    this.RaisePropertyChanged("Summ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TaxPremium {
            get {
                return this.TaxPremiumField;
            }
            set {
                if ((this.TaxPremiumField.Equals(value) != true)) {
                    this.TaxPremiumField = value;
                    this.RaisePropertyChanged("TaxPremium");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal XOCPPremium {
            get {
                return this.XOCPPremiumField;
            }
            set {
                if ((this.XOCPPremiumField.Equals(value) != true)) {
                    this.XOCPPremiumField = value;
                    this.RaisePropertyChanged("XOCPPremium");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal XTRPremium {
            get {
                return this.XTRPremiumField;
            }
            set {
                if ((this.XTRPremiumField.Equals(value) != true)) {
                    this.XTRPremiumField = value;
                    this.RaisePropertyChanged("XTRPremium");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://NewISISService/2012/ISISAppTransportService", ConfigurationName="IsisAppTransportService.IAppTransportServiceContract")]
    public interface IAppTransportServiceContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/C" +
            "hangeAppFormStatus", ReplyAction="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/C" +
            "hangeAppFormStatusResponse")]
        void ChangeAppFormStatus(string appRegisterID, string status, string subStatus, string detail, System.DateTime requestDate, int gracePeriod, long isisDocID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/G" +
            "etAppFormContentByID", ReplyAction="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/G" +
            "etAppFormContentByIDResponse")]
        byte[] GetAppFormContentByID(string appRegisterID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/G" +
            "etMoreContentByID", ReplyAction="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/G" +
            "etMoreContentByIDResponse")]
        byte[] GetMoreContentByID(string responseID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/G" +
            "etContentByID", ReplyAction="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/G" +
            "etContentByIDResponse")]
        byte[] GetContentByID(string contentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/S" +
            "endCompleteContentStatus", ReplyAction="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/S" +
            "endCompleteContentStatusResponse")]
        void SendCompleteContentStatus(string appRegisterID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/S" +
            "endReceiveContentStatusToOutSide", ReplyAction="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/S" +
            "endReceiveContentStatusToOutSideResponse")]
        void SendReceiveContentStatusToOutSide(string appRegisterID, string isisDocID, string receiveBranchCode, string createdBy, string contentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/R" +
            "equestToIssueNewPolicy", ReplyAction="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/R" +
            "equestToIssueNewPolicyResponse")]
        void RequestToIssueNewPolicy(string appRegisterID, ref NewBisPA.IsisAppTransportService.OrdBilling billing);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/R" +
            "equestToCancelBill", ReplyAction="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/R" +
            "equestToCancelBillResponse")]
        void RequestToCancelBill(NewBisPA.IsisAppTransportService.OrdBillingCancel billingCancel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/R" +
            "equestToIssueNewBill", ReplyAction="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/R" +
            "equestToIssueNewBillResponse")]
        void RequestToIssueNewBill(ref NewBisPA.IsisAppTransportService.OrdBilling billing);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/S" +
            "endScanRatingSheetCompleteToOutSide", ReplyAction="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/S" +
            "endScanRatingSheetCompleteToOutSideResponse")]
        void SendScanRatingSheetCompleteToOutSide(string appRegisterID, string createdBy, string contentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/S" +
            "endScanOtherDocCompleteToOutSide", ReplyAction="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/S" +
            "endScanOtherDocCompleteToOutSideResponse")]
        void SendScanOtherDocCompleteToOutSide(string appRegisterID, string blaBranchCode, string createdBy, string contentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/U" +
            "pdateTaxPremium", ReplyAction="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/U" +
            "pdateTaxPremiumResponse")]
        void UpdateTaxPremium();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAppTransportServiceContractChannel : NewBisPA.IsisAppTransportService.IAppTransportServiceContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AppTransportServiceContractClient : System.ServiceModel.ClientBase<NewBisPA.IsisAppTransportService.IAppTransportServiceContract>, NewBisPA.IsisAppTransportService.IAppTransportServiceContract {
        
        public AppTransportServiceContractClient() {
        }
        
        public AppTransportServiceContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AppTransportServiceContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AppTransportServiceContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AppTransportServiceContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ChangeAppFormStatus(string appRegisterID, string status, string subStatus, string detail, System.DateTime requestDate, int gracePeriod, long isisDocID) {
            base.Channel.ChangeAppFormStatus(appRegisterID, status, subStatus, detail, requestDate, gracePeriod, isisDocID);
        }
        
        public byte[] GetAppFormContentByID(string appRegisterID) {
            return base.Channel.GetAppFormContentByID(appRegisterID);
        }
        
        public byte[] GetMoreContentByID(string responseID) {
            return base.Channel.GetMoreContentByID(responseID);
        }
        
        public byte[] GetContentByID(string contentID) {
            return base.Channel.GetContentByID(contentID);
        }
        
        public void SendCompleteContentStatus(string appRegisterID) {
            base.Channel.SendCompleteContentStatus(appRegisterID);
        }
        
        public void SendReceiveContentStatusToOutSide(string appRegisterID, string isisDocID, string receiveBranchCode, string createdBy, string contentID) {
            base.Channel.SendReceiveContentStatusToOutSide(appRegisterID, isisDocID, receiveBranchCode, createdBy, contentID);
        }
        
        public void RequestToIssueNewPolicy(string appRegisterID, ref NewBisPA.IsisAppTransportService.OrdBilling billing) {
            base.Channel.RequestToIssueNewPolicy(appRegisterID, ref billing);
        }
        
        public void RequestToCancelBill(NewBisPA.IsisAppTransportService.OrdBillingCancel billingCancel) {
            base.Channel.RequestToCancelBill(billingCancel);
        }
        
        public void RequestToIssueNewBill(ref NewBisPA.IsisAppTransportService.OrdBilling billing) {
            base.Channel.RequestToIssueNewBill(ref billing);
        }
        
        public void SendScanRatingSheetCompleteToOutSide(string appRegisterID, string createdBy, string contentID) {
            base.Channel.SendScanRatingSheetCompleteToOutSide(appRegisterID, createdBy, contentID);
        }
        
        public void SendScanOtherDocCompleteToOutSide(string appRegisterID, string blaBranchCode, string createdBy, string contentID) {
            base.Channel.SendScanOtherDocCompleteToOutSide(appRegisterID, blaBranchCode, createdBy, contentID);
        }
        
        public void UpdateTaxPremium() {
            base.Channel.UpdateTaxPremium();
        }
    }
}
