//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewBisPA.AccountSvcRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PayOptionCode", Namespace="http://schemas.datacontract.org/2004/07/Account.DataContract")]
    public enum PayOptionCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CQ = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DF = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TF = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CC = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ACCOUNT_PAY_OPTION", Namespace="http://schemas.datacontract.org/2004/07/Account.DataContract")]
    [System.SerializableAttribute()]
    public partial class ACCOUNT_PAY_OPTION : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NewBisPA.AccountSvcRef.PayOptionCode NumCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NewBisPA.AccountSvcRef.PayOptionCode NumCode {
            get {
                return this.NumCodeField;
            }
            set {
                if ((this.NumCodeField.Equals(value) != true)) {
                    this.NumCodeField = value;
                    this.RaisePropertyChanged("NumCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AccountSvcRef.IAccountService")]
    public interface IAccountService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/INS_AC_WAITPAY", ReplyAction="http://tempuri.org/IAccountService/INS_AC_WAITPAYResponse")]
        System.Nullable<decimal> INS_AC_WAITPAY(out ITUtility.ProcessResult pr, string IN_JOB_CODE, System.Nullable<decimal> IN_JOB_ID, string IN_PAY_OPTION, string IN_BANK, string IN_BRANCH, string IN_ACCOUNT_NO, System.Nullable<decimal> IN_PAY, string IN_PAY_NAME, string IN_OPERATION, string IN_UPD_ID, string IN_CHANNEL_TYPE, string IN_PL_BLOCK);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/INS_AC_WAITPAY_ACCCODE", ReplyAction="http://tempuri.org/IAccountService/INS_AC_WAITPAY_ACCCODEResponse")]
        System.Nullable<decimal> INS_AC_WAITPAY_ACCCODE(out ITUtility.ProcessResult pr, System.Nullable<decimal> IN_AC_WAITPAY_ID, string IN_ACCCODE, System.Nullable<decimal> IN_PAY);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/GetAccountPayOption", ReplyAction="http://tempuri.org/IAccountService/GetAccountPayOptionResponse")]
        NewBisPA.AccountSvcRef.ACCOUNT_PAY_OPTION GetAccountPayOption(out ITUtility.ProcessResult pr, NewBisPA.AccountSvcRef.PayOptionCode code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/GET_AC_OPTPAY_BYREFID", ReplyAction="http://tempuri.org/IAccountService/GET_AC_OPTPAY_BYREFIDResponse")]
        ITUtility.ProcessResult GET_AC_OPTPAY_BYREFID(out string OUT_PAY_OPTION, out string OUT_BANK, out string OUT_BRANCH, out string OUT_ACCNO, out string OUT_PAY_NAME, out System.Nullable<System.DateTime> OUT_PAY_DT, string IN_JOB_CODE, System.Nullable<decimal> IN_JOB_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/GET_AC_OPTPAY_BYREFID_V2", ReplyAction="http://tempuri.org/IAccountService/GET_AC_OPTPAY_BYREFID_V2Response")]
        ITUtility.ProcessResult GET_AC_OPTPAY_BYREFID_V2(out string OUT_PAY_OPTION, out string OUT_BANK, out string OUT_BRANCH, out string OUT_ACCNO, out string OUT_PAY_NAME, out System.Nullable<System.DateTime> OUT_PAY_DT, out System.Nullable<decimal> OUT_PAY, string IN_JOB_CODE, System.Nullable<decimal> IN_JOB_ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAccountServiceChannel : NewBisPA.AccountSvcRef.IAccountService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountServiceClient : System.ServiceModel.ClientBase<NewBisPA.AccountSvcRef.IAccountService>, NewBisPA.AccountSvcRef.IAccountService {
        
        public AccountServiceClient() {
        }
        
        public AccountServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Nullable<decimal> INS_AC_WAITPAY(out ITUtility.ProcessResult pr, string IN_JOB_CODE, System.Nullable<decimal> IN_JOB_ID, string IN_PAY_OPTION, string IN_BANK, string IN_BRANCH, string IN_ACCOUNT_NO, System.Nullable<decimal> IN_PAY, string IN_PAY_NAME, string IN_OPERATION, string IN_UPD_ID, string IN_CHANNEL_TYPE, string IN_PL_BLOCK) {
            return base.Channel.INS_AC_WAITPAY(out pr, IN_JOB_CODE, IN_JOB_ID, IN_PAY_OPTION, IN_BANK, IN_BRANCH, IN_ACCOUNT_NO, IN_PAY, IN_PAY_NAME, IN_OPERATION, IN_UPD_ID, IN_CHANNEL_TYPE, IN_PL_BLOCK);
        }
        
        public System.Nullable<decimal> INS_AC_WAITPAY_ACCCODE(out ITUtility.ProcessResult pr, System.Nullable<decimal> IN_AC_WAITPAY_ID, string IN_ACCCODE, System.Nullable<decimal> IN_PAY) {
            return base.Channel.INS_AC_WAITPAY_ACCCODE(out pr, IN_AC_WAITPAY_ID, IN_ACCCODE, IN_PAY);
        }
        
        public NewBisPA.AccountSvcRef.ACCOUNT_PAY_OPTION GetAccountPayOption(out ITUtility.ProcessResult pr, NewBisPA.AccountSvcRef.PayOptionCode code) {
            return base.Channel.GetAccountPayOption(out pr, code);
        }
        
        public ITUtility.ProcessResult GET_AC_OPTPAY_BYREFID(out string OUT_PAY_OPTION, out string OUT_BANK, out string OUT_BRANCH, out string OUT_ACCNO, out string OUT_PAY_NAME, out System.Nullable<System.DateTime> OUT_PAY_DT, string IN_JOB_CODE, System.Nullable<decimal> IN_JOB_ID) {
            return base.Channel.GET_AC_OPTPAY_BYREFID(out OUT_PAY_OPTION, out OUT_BANK, out OUT_BRANCH, out OUT_ACCNO, out OUT_PAY_NAME, out OUT_PAY_DT, IN_JOB_CODE, IN_JOB_ID);
        }
        
        public ITUtility.ProcessResult GET_AC_OPTPAY_BYREFID_V2(out string OUT_PAY_OPTION, out string OUT_BANK, out string OUT_BRANCH, out string OUT_ACCNO, out string OUT_PAY_NAME, out System.Nullable<System.DateTime> OUT_PAY_DT, out System.Nullable<decimal> OUT_PAY, string IN_JOB_CODE, System.Nullable<decimal> IN_JOB_ID) {
            return base.Channel.GET_AC_OPTPAY_BYREFID_V2(out OUT_PAY_OPTION, out OUT_BANK, out OUT_BRANCH, out OUT_ACCNO, out OUT_PAY_NAME, out OUT_PAY_DT, out OUT_PAY, IN_JOB_CODE, IN_JOB_ID);
        }
    }
}
