//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewBisPA.CenterSvcRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/CenterProvider")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobilePhoneNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OfficeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OfficeDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OldUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrgDescTHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrgIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PreNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdateByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UpdateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mail {
            get {
                return this.MailField;
            }
            set {
                if ((object.ReferenceEquals(this.MailField, value) != true)) {
                    this.MailField = value;
                    this.RaisePropertyChanged("Mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobilePhoneNo {
            get {
                return this.MobilePhoneNoField;
            }
            set {
                if ((object.ReferenceEquals(this.MobilePhoneNoField, value) != true)) {
                    this.MobilePhoneNoField = value;
                    this.RaisePropertyChanged("MobilePhoneNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OfficeCode {
            get {
                return this.OfficeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.OfficeCodeField, value) != true)) {
                    this.OfficeCodeField = value;
                    this.RaisePropertyChanged("OfficeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OfficeDesc {
            get {
                return this.OfficeDescField;
            }
            set {
                if ((object.ReferenceEquals(this.OfficeDescField, value) != true)) {
                    this.OfficeDescField = value;
                    this.RaisePropertyChanged("OfficeDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OldUserId {
            get {
                return this.OldUserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.OldUserIdField, value) != true)) {
                    this.OldUserIdField = value;
                    this.RaisePropertyChanged("OldUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrgDescTH {
            get {
                return this.OrgDescTHField;
            }
            set {
                if ((object.ReferenceEquals(this.OrgDescTHField, value) != true)) {
                    this.OrgDescTHField = value;
                    this.RaisePropertyChanged("OrgDescTH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrgID {
            get {
                return this.OrgIDField;
            }
            set {
                if ((this.OrgIDField.Equals(value) != true)) {
                    this.OrgIDField = value;
                    this.RaisePropertyChanged("OrgID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreName {
            get {
                return this.PreNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PreNameField, value) != true)) {
                    this.PreNameField = value;
                    this.RaisePropertyChanged("PreName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdateBy {
            get {
                return this.UpdateByField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdateByField, value) != true)) {
                    this.UpdateByField = value;
                    this.RaisePropertyChanged("UpdateBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpdateDate {
            get {
                return this.UpdateDateField;
            }
            set {
                if ((this.UpdateDateField.Equals(value) != true)) {
                    this.UpdateDateField = value;
                    this.RaisePropertyChanged("UpdateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIDField, value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameField, value) != true)) {
                    this.firstNameField = value;
                    this.RaisePropertyChanged("firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastNameField, value) != true)) {
                    this.lastNameField = value;
                    this.RaisePropertyChanged("lastName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessResult", Namespace="http://schemas.datacontract.org/2004/07/CenterProvider")]
    [System.SerializableAttribute()]
    public partial class ProcessResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Successed {
            get {
                return this.SuccessedField;
            }
            set {
                if ((this.SuccessedField.Equals(value) != true)) {
                    this.SuccessedField = value;
                    this.RaisePropertyChanged("Successed");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserSearch", Namespace="http://schemas.datacontract.org/2004/07/CenterProvider")]
    [System.SerializableAttribute()]
    public partial class UserSearch : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IncludeSubOrgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OfficeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrgDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrgIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IncludeSubOrg {
            get {
                return this.IncludeSubOrgField;
            }
            set {
                if ((this.IncludeSubOrgField.Equals(value) != true)) {
                    this.IncludeSubOrgField = value;
                    this.RaisePropertyChanged("IncludeSubOrg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Office {
            get {
                return this.OfficeField;
            }
            set {
                if ((object.ReferenceEquals(this.OfficeField, value) != true)) {
                    this.OfficeField = value;
                    this.RaisePropertyChanged("Office");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrgDesc {
            get {
                return this.OrgDescField;
            }
            set {
                if ((object.ReferenceEquals(this.OrgDescField, value) != true)) {
                    this.OrgDescField = value;
                    this.RaisePropertyChanged("OrgDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrgID {
            get {
                return this.OrgIDField;
            }
            set {
                if ((this.OrgIDField.Equals(value) != true)) {
                    this.OrgIDField = value;
                    this.RaisePropertyChanged("OrgID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Organization", Namespace="http://schemas.datacontract.org/2004/07/CenterProvider")]
    [System.SerializableAttribute()]
    public partial class Organization : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartDescENField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartDescTHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescENField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescTHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DivCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DivDescENField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DivDescTHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LineCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LineDescENField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LineDescTHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdateByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UpdateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UplineCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UplineDescENField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UplineDescTHField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartCode {
            get {
                return this.DepartCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartCodeField, value) != true)) {
                    this.DepartCodeField = value;
                    this.RaisePropertyChanged("DepartCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartDescEN {
            get {
                return this.DepartDescENField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartDescENField, value) != true)) {
                    this.DepartDescENField = value;
                    this.RaisePropertyChanged("DepartDescEN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartDescTH {
            get {
                return this.DepartDescTHField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartDescTHField, value) != true)) {
                    this.DepartDescTHField = value;
                    this.RaisePropertyChanged("DepartDescTH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescEN {
            get {
                return this.DescENField;
            }
            set {
                if ((object.ReferenceEquals(this.DescENField, value) != true)) {
                    this.DescENField = value;
                    this.RaisePropertyChanged("DescEN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescTH {
            get {
                return this.DescTHField;
            }
            set {
                if ((object.ReferenceEquals(this.DescTHField, value) != true)) {
                    this.DescTHField = value;
                    this.RaisePropertyChanged("DescTH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DivCode {
            get {
                return this.DivCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DivCodeField, value) != true)) {
                    this.DivCodeField = value;
                    this.RaisePropertyChanged("DivCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DivDescEN {
            get {
                return this.DivDescENField;
            }
            set {
                if ((object.ReferenceEquals(this.DivDescENField, value) != true)) {
                    this.DivDescENField = value;
                    this.RaisePropertyChanged("DivDescEN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DivDescTH {
            get {
                return this.DivDescTHField;
            }
            set {
                if ((object.ReferenceEquals(this.DivDescTHField, value) != true)) {
                    this.DivDescTHField = value;
                    this.RaisePropertyChanged("DivDescTH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Level {
            get {
                return this.LevelField;
            }
            set {
                if ((this.LevelField.Equals(value) != true)) {
                    this.LevelField = value;
                    this.RaisePropertyChanged("Level");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LineCode {
            get {
                return this.LineCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LineCodeField, value) != true)) {
                    this.LineCodeField = value;
                    this.RaisePropertyChanged("LineCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LineDescEN {
            get {
                return this.LineDescENField;
            }
            set {
                if ((object.ReferenceEquals(this.LineDescENField, value) != true)) {
                    this.LineDescENField = value;
                    this.RaisePropertyChanged("LineDescEN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LineDescTH {
            get {
                return this.LineDescTHField;
            }
            set {
                if ((object.ReferenceEquals(this.LineDescTHField, value) != true)) {
                    this.LineDescTHField = value;
                    this.RaisePropertyChanged("LineDescTH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdateBy {
            get {
                return this.UpdateByField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdateByField, value) != true)) {
                    this.UpdateByField = value;
                    this.RaisePropertyChanged("UpdateBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpdateDate {
            get {
                return this.UpdateDateField;
            }
            set {
                if ((this.UpdateDateField.Equals(value) != true)) {
                    this.UpdateDateField = value;
                    this.RaisePropertyChanged("UpdateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UplineCode {
            get {
                return this.UplineCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.UplineCodeField, value) != true)) {
                    this.UplineCodeField = value;
                    this.RaisePropertyChanged("UplineCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UplineDescEN {
            get {
                return this.UplineDescENField;
            }
            set {
                if ((object.ReferenceEquals(this.UplineDescENField, value) != true)) {
                    this.UplineDescENField = value;
                    this.RaisePropertyChanged("UplineDescEN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UplineDescTH {
            get {
                return this.UplineDescTHField;
            }
            set {
                if ((object.ReferenceEquals(this.UplineDescTHField, value) != true)) {
                    this.UplineDescTHField = value;
                    this.RaisePropertyChanged("UplineDescTH");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Office", Namespace="http://schemas.datacontract.org/2004/07/CenterProvider")]
    [System.SerializableAttribute()]
    public partial class Office : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OldCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OldCode {
            get {
                return this.OldCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.OldCodeField, value) != true)) {
                    this.OldCodeField = value;
                    this.RaisePropertyChanged("OldCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CenterSvcRef.ICenterService")]
    public interface ICenterService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICenterService/getUser", ReplyAction="http://tempuri.org/ICenterService/getUserResponse")]
        NewBisPA.CenterSvcRef.User getUser(out NewBisPA.CenterSvcRef.ProcessResult processResult, string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICenterService/getUserCollection", ReplyAction="http://tempuri.org/ICenterService/getUserCollectionResponse")]
        NewBisPA.CenterSvcRef.User[] getUserCollection(out NewBisPA.CenterSvcRef.ProcessResult processResult, NewBisPA.CenterSvcRef.UserSearch search);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICenterService/GetUserByIds", ReplyAction="http://tempuri.org/ICenterService/GetUserByIdsResponse")]
        ITUtility.ProcessResult GetUserByIds(out NewBisPA.CenterSvcRef.User[] returnObjects, string[] userIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICenterService/getOrganizationCollection", ReplyAction="http://tempuri.org/ICenterService/getOrganizationCollectionResponse")]
        NewBisPA.CenterSvcRef.Organization[] getOrganizationCollection(out NewBisPA.CenterSvcRef.ProcessResult processResult);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICenterService/getOrganizationByCode", ReplyAction="http://tempuri.org/ICenterService/getOrganizationByCodeResponse")]
        NewBisPA.CenterSvcRef.Organization getOrganizationByCode(out NewBisPA.CenterSvcRef.ProcessResult processResult, string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICenterService/getOrganizationById", ReplyAction="http://tempuri.org/ICenterService/getOrganizationByIdResponse")]
        NewBisPA.CenterSvcRef.Organization getOrganizationById(out NewBisPA.CenterSvcRef.ProcessResult processResult, long orgID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICenterService/GetOffice", ReplyAction="http://tempuri.org/ICenterService/GetOfficeResponse")]
        NewBisPA.CenterSvcRef.Office[] GetOffice(out NewBisPA.CenterSvcRef.ProcessResult pr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICenterService/GetOfficeByIsoRegion", ReplyAction="http://tempuri.org/ICenterService/GetOfficeByIsoRegionResponse")]
        NewBisPA.CenterSvcRef.Office[] GetOfficeByIsoRegion(out NewBisPA.CenterSvcRef.ProcessResult processResult, string iso_flg, string app_region);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICenterService/GetOfficeByCode", ReplyAction="http://tempuri.org/ICenterService/GetOfficeByCodeResponse")]
        NewBisPA.CenterSvcRef.Office GetOfficeByCode(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICenterService/GetOrganization", ReplyAction="http://tempuri.org/ICenterService/GetOrganizationResponse")]
        NewBisPA.CenterSvcRef.Organization[] GetOrganization(out NewBisPA.CenterSvcRef.ProcessResult processResult, long[] orgId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICenterService/GetOfficeByCodeArray", ReplyAction="http://tempuri.org/ICenterService/GetOfficeByCodeArrayResponse")]
        NewBisPA.CenterSvcRef.Office[] GetOfficeByCodeArray(out NewBisPA.CenterSvcRef.ProcessResult processResult, string[] code);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICenterServiceChannel : NewBisPA.CenterSvcRef.ICenterService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CenterServiceClient : System.ServiceModel.ClientBase<NewBisPA.CenterSvcRef.ICenterService>, NewBisPA.CenterSvcRef.ICenterService {
        
        public CenterServiceClient() {
        }
        
        public CenterServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CenterServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CenterServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CenterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public NewBisPA.CenterSvcRef.User getUser(out NewBisPA.CenterSvcRef.ProcessResult processResult, string code) {
            return base.Channel.getUser(out processResult, code);
        }
        
        public NewBisPA.CenterSvcRef.User[] getUserCollection(out NewBisPA.CenterSvcRef.ProcessResult processResult, NewBisPA.CenterSvcRef.UserSearch search) {
            return base.Channel.getUserCollection(out processResult, search);
        }
        
        public ITUtility.ProcessResult GetUserByIds(out NewBisPA.CenterSvcRef.User[] returnObjects, string[] userIds) {
            return base.Channel.GetUserByIds(out returnObjects, userIds);
        }
        
        public NewBisPA.CenterSvcRef.Organization[] getOrganizationCollection(out NewBisPA.CenterSvcRef.ProcessResult processResult) {
            return base.Channel.getOrganizationCollection(out processResult);
        }
        
        public NewBisPA.CenterSvcRef.Organization getOrganizationByCode(out NewBisPA.CenterSvcRef.ProcessResult processResult, string code) {
            return base.Channel.getOrganizationByCode(out processResult, code);
        }
        
        public NewBisPA.CenterSvcRef.Organization getOrganizationById(out NewBisPA.CenterSvcRef.ProcessResult processResult, long orgID) {
            return base.Channel.getOrganizationById(out processResult, orgID);
        }
        
        public NewBisPA.CenterSvcRef.Office[] GetOffice(out NewBisPA.CenterSvcRef.ProcessResult pr) {
            return base.Channel.GetOffice(out pr);
        }
        
        public NewBisPA.CenterSvcRef.Office[] GetOfficeByIsoRegion(out NewBisPA.CenterSvcRef.ProcessResult processResult, string iso_flg, string app_region) {
            return base.Channel.GetOfficeByIsoRegion(out processResult, iso_flg, app_region);
        }
        
        public NewBisPA.CenterSvcRef.Office GetOfficeByCode(string code) {
            return base.Channel.GetOfficeByCode(code);
        }
        
        public NewBisPA.CenterSvcRef.Organization[] GetOrganization(out NewBisPA.CenterSvcRef.ProcessResult processResult, long[] orgId) {
            return base.Channel.GetOrganization(out processResult, orgId);
        }
        
        public NewBisPA.CenterSvcRef.Office[] GetOfficeByCodeArray(out NewBisPA.CenterSvcRef.ProcessResult processResult, string[] code) {
            return base.Channel.GetOfficeByCodeArray(out processResult, code);
        }
    }
}
