//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewBisPA.LetterSvcRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LS_FILE_CONTROL_LOG", Namespace="http://schemas.datacontract.org/2004/07/LetterService")]
    [System.SerializableAttribute()]
    public partial class LS_FILE_CONTROL_LOG : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ACCESS_DATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> APPLICATION_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CONTENT_TYPEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> CONTROL_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CREATE_BYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CREATE_DATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DESCRIPTIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DOWNLOADEDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FILE_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FILE_PATHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OFFICEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> ORG_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UPDATE_BYField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ACCESS_DATE {
            get {
                return this.ACCESS_DATEField;
            }
            set {
                if ((this.ACCESS_DATEField.Equals(value) != true)) {
                    this.ACCESS_DATEField = value;
                    this.RaisePropertyChanged("ACCESS_DATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> APPLICATION_ID {
            get {
                return this.APPLICATION_IDField;
            }
            set {
                if ((this.APPLICATION_IDField.Equals(value) != true)) {
                    this.APPLICATION_IDField = value;
                    this.RaisePropertyChanged("APPLICATION_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CONTENT_TYPE {
            get {
                return this.CONTENT_TYPEField;
            }
            set {
                if ((object.ReferenceEquals(this.CONTENT_TYPEField, value) != true)) {
                    this.CONTENT_TYPEField = value;
                    this.RaisePropertyChanged("CONTENT_TYPE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> CONTROL_ID {
            get {
                return this.CONTROL_IDField;
            }
            set {
                if ((this.CONTROL_IDField.Equals(value) != true)) {
                    this.CONTROL_IDField = value;
                    this.RaisePropertyChanged("CONTROL_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CREATE_BY {
            get {
                return this.CREATE_BYField;
            }
            set {
                if ((object.ReferenceEquals(this.CREATE_BYField, value) != true)) {
                    this.CREATE_BYField = value;
                    this.RaisePropertyChanged("CREATE_BY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CREATE_DATE {
            get {
                return this.CREATE_DATEField;
            }
            set {
                if ((this.CREATE_DATEField.Equals(value) != true)) {
                    this.CREATE_DATEField = value;
                    this.RaisePropertyChanged("CREATE_DATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESCRIPTION {
            get {
                return this.DESCRIPTIONField;
            }
            set {
                if ((object.ReferenceEquals(this.DESCRIPTIONField, value) != true)) {
                    this.DESCRIPTIONField = value;
                    this.RaisePropertyChanged("DESCRIPTION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DOWNLOADED {
            get {
                return this.DOWNLOADEDField;
            }
            set {
                if ((object.ReferenceEquals(this.DOWNLOADEDField, value) != true)) {
                    this.DOWNLOADEDField = value;
                    this.RaisePropertyChanged("DOWNLOADED");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FILE_NAME {
            get {
                return this.FILE_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.FILE_NAMEField, value) != true)) {
                    this.FILE_NAMEField = value;
                    this.RaisePropertyChanged("FILE_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FILE_PATH {
            get {
                return this.FILE_PATHField;
            }
            set {
                if ((object.ReferenceEquals(this.FILE_PATHField, value) != true)) {
                    this.FILE_PATHField = value;
                    this.RaisePropertyChanged("FILE_PATH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OFFICE {
            get {
                return this.OFFICEField;
            }
            set {
                if ((object.ReferenceEquals(this.OFFICEField, value) != true)) {
                    this.OFFICEField = value;
                    this.RaisePropertyChanged("OFFICE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> ORG_ID {
            get {
                return this.ORG_IDField;
            }
            set {
                if ((this.ORG_IDField.Equals(value) != true)) {
                    this.ORG_IDField = value;
                    this.RaisePropertyChanged("ORG_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UPDATE_BY {
            get {
                return this.UPDATE_BYField;
            }
            set {
                if ((object.ReferenceEquals(this.UPDATE_BYField, value) != true)) {
                    this.UPDATE_BYField = value;
                    this.RaisePropertyChanged("UPDATE_BY");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentFile", Namespace="http://schemas.datacontract.org/2004/07/LetterService")]
    [System.SerializableAttribute()]
    public partial class DocumentFile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FileDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ModifyDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] FileData {
            get {
                return this.FileDataField;
            }
            set {
                if ((object.ReferenceEquals(this.FileDataField, value) != true)) {
                    this.FileDataField = value;
                    this.RaisePropertyChanged("FileData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifyDate {
            get {
                return this.ModifyDateField;
            }
            set {
                if ((this.ModifyDateField.Equals(value) != true)) {
                    this.ModifyDateField = value;
                    this.RaisePropertyChanged("ModifyDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LS_FILE_CONTROL", Namespace="http://schemas.datacontract.org/2004/07/LetterService")]
    [System.SerializableAttribute()]
    public partial class LS_FILE_CONTROL : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> APPLICATION_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string APPLICATION_ID2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CONTENT_TYPEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> CONTROL_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CONTROL_ID2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CREATE_BYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CREATE_DATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DESCRIPTIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FILE_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FILE_PATHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OFFICEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> ORG_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ORG_ID2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UPDATE_BYField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> APPLICATION_ID {
            get {
                return this.APPLICATION_IDField;
            }
            set {
                if ((this.APPLICATION_IDField.Equals(value) != true)) {
                    this.APPLICATION_IDField = value;
                    this.RaisePropertyChanged("APPLICATION_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string APPLICATION_ID2 {
            get {
                return this.APPLICATION_ID2Field;
            }
            set {
                if ((object.ReferenceEquals(this.APPLICATION_ID2Field, value) != true)) {
                    this.APPLICATION_ID2Field = value;
                    this.RaisePropertyChanged("APPLICATION_ID2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CONTENT_TYPE {
            get {
                return this.CONTENT_TYPEField;
            }
            set {
                if ((object.ReferenceEquals(this.CONTENT_TYPEField, value) != true)) {
                    this.CONTENT_TYPEField = value;
                    this.RaisePropertyChanged("CONTENT_TYPE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> CONTROL_ID {
            get {
                return this.CONTROL_IDField;
            }
            set {
                if ((this.CONTROL_IDField.Equals(value) != true)) {
                    this.CONTROL_IDField = value;
                    this.RaisePropertyChanged("CONTROL_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CONTROL_ID2 {
            get {
                return this.CONTROL_ID2Field;
            }
            set {
                if ((object.ReferenceEquals(this.CONTROL_ID2Field, value) != true)) {
                    this.CONTROL_ID2Field = value;
                    this.RaisePropertyChanged("CONTROL_ID2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CREATE_BY {
            get {
                return this.CREATE_BYField;
            }
            set {
                if ((object.ReferenceEquals(this.CREATE_BYField, value) != true)) {
                    this.CREATE_BYField = value;
                    this.RaisePropertyChanged("CREATE_BY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CREATE_DATE {
            get {
                return this.CREATE_DATEField;
            }
            set {
                if ((this.CREATE_DATEField.Equals(value) != true)) {
                    this.CREATE_DATEField = value;
                    this.RaisePropertyChanged("CREATE_DATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESCRIPTION {
            get {
                return this.DESCRIPTIONField;
            }
            set {
                if ((object.ReferenceEquals(this.DESCRIPTIONField, value) != true)) {
                    this.DESCRIPTIONField = value;
                    this.RaisePropertyChanged("DESCRIPTION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FILE_NAME {
            get {
                return this.FILE_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.FILE_NAMEField, value) != true)) {
                    this.FILE_NAMEField = value;
                    this.RaisePropertyChanged("FILE_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FILE_PATH {
            get {
                return this.FILE_PATHField;
            }
            set {
                if ((object.ReferenceEquals(this.FILE_PATHField, value) != true)) {
                    this.FILE_PATHField = value;
                    this.RaisePropertyChanged("FILE_PATH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OFFICE {
            get {
                return this.OFFICEField;
            }
            set {
                if ((object.ReferenceEquals(this.OFFICEField, value) != true)) {
                    this.OFFICEField = value;
                    this.RaisePropertyChanged("OFFICE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> ORG_ID {
            get {
                return this.ORG_IDField;
            }
            set {
                if ((this.ORG_IDField.Equals(value) != true)) {
                    this.ORG_IDField = value;
                    this.RaisePropertyChanged("ORG_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ORG_ID2 {
            get {
                return this.ORG_ID2Field;
            }
            set {
                if ((object.ReferenceEquals(this.ORG_ID2Field, value) != true)) {
                    this.ORG_ID2Field = value;
                    this.RaisePropertyChanged("ORG_ID2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UPDATE_BY {
            get {
                return this.UPDATE_BYField;
            }
            set {
                if ((object.ReferenceEquals(this.UPDATE_BYField, value) != true)) {
                    this.UPDATE_BYField = value;
                    this.RaisePropertyChanged("UPDATE_BY");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LS_SETTING", Namespace="http://schemas.datacontract.org/2004/07/LetterService")]
    [System.SerializableAttribute()]
    public partial class LS_SETTING : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ROOT_DIRECTORYField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ROOT_DIRECTORY {
            get {
                return this.ROOT_DIRECTORYField;
            }
            set {
                if ((object.ReferenceEquals(this.ROOT_DIRECTORYField, value) != true)) {
                    this.ROOT_DIRECTORYField = value;
                    this.RaisePropertyChanged("ROOT_DIRECTORY");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mail", Namespace="http://schemas.datacontract.org/2004/07/LetterService")]
    [System.SerializableAttribute()]
    public partial class Mail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NewBisPA.LetterSvcRef.DataFileCollection AttachFileCollectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] CcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NewBisPA.LetterSvcRef.MailEncoding EncodingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsBodyHtmlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ToField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NewBisPA.LetterSvcRef.DataFileCollection AttachFileCollection {
            get {
                return this.AttachFileCollectionField;
            }
            set {
                if ((object.ReferenceEquals(this.AttachFileCollectionField, value) != true)) {
                    this.AttachFileCollectionField = value;
                    this.RaisePropertyChanged("AttachFileCollection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Body {
            get {
                return this.BodyField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyField, value) != true)) {
                    this.BodyField = value;
                    this.RaisePropertyChanged("Body");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Cc {
            get {
                return this.CcField;
            }
            set {
                if ((object.ReferenceEquals(this.CcField, value) != true)) {
                    this.CcField = value;
                    this.RaisePropertyChanged("Cc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NewBisPA.LetterSvcRef.MailEncoding Encoding {
            get {
                return this.EncodingField;
            }
            set {
                if ((this.EncodingField.Equals(value) != true)) {
                    this.EncodingField = value;
                    this.RaisePropertyChanged("Encoding");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string From {
            get {
                return this.FromField;
            }
            set {
                if ((object.ReferenceEquals(this.FromField, value) != true)) {
                    this.FromField = value;
                    this.RaisePropertyChanged("From");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsBodyHtml {
            get {
                return this.IsBodyHtmlField;
            }
            set {
                if ((this.IsBodyHtmlField.Equals(value) != true)) {
                    this.IsBodyHtmlField = value;
                    this.RaisePropertyChanged("IsBodyHtml");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] To {
            get {
                return this.ToField;
            }
            set {
                if ((object.ReferenceEquals(this.ToField, value) != true)) {
                    this.ToField = value;
                    this.RaisePropertyChanged("To");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="DataFileCollection", Namespace="http://schemas.datacontract.org/2004/07/ITUtility", ItemName="DataFile")]
    [System.SerializableAttribute()]
    public class DataFileCollection : System.Collections.Generic.List<ITUtility.DataFile> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MailEncoding", Namespace="http://schemas.datacontract.org/2004/07/LetterService")]
    public enum MailEncoding : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Windows874 = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UTF8 = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Recipient", Namespace="http://schemas.datacontract.org/2004/07/LetterService")]
    [System.SerializableAttribute()]
    public partial class Recipient : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobilePhoneNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobilePhoneNo {
            get {
                return this.MobilePhoneNoField;
            }
            set {
                if ((object.ReferenceEquals(this.MobilePhoneNoField, value) != true)) {
                    this.MobilePhoneNoField = value;
                    this.RaisePropertyChanged("MobilePhoneNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIDField, value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SMS", Namespace="http://schemas.datacontract.org/2004/07/LetterService")]
    [System.SerializableAttribute()]
    public partial class SMS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MESSAGEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OFFICEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PASSKEYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NewBisPA.LetterSvcRef.Recipient_Collection Recipient_CollectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> SEND_DTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SEND_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ZTB_ORG_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ZTB_SMS_TYPE_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MESSAGE {
            get {
                return this.MESSAGEField;
            }
            set {
                if ((object.ReferenceEquals(this.MESSAGEField, value) != true)) {
                    this.MESSAGEField = value;
                    this.RaisePropertyChanged("MESSAGE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OFFICE {
            get {
                return this.OFFICEField;
            }
            set {
                if ((object.ReferenceEquals(this.OFFICEField, value) != true)) {
                    this.OFFICEField = value;
                    this.RaisePropertyChanged("OFFICE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PASSKEY {
            get {
                return this.PASSKEYField;
            }
            set {
                if ((object.ReferenceEquals(this.PASSKEYField, value) != true)) {
                    this.PASSKEYField = value;
                    this.RaisePropertyChanged("PASSKEY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NewBisPA.LetterSvcRef.Recipient_Collection Recipient_Collection {
            get {
                return this.Recipient_CollectionField;
            }
            set {
                if ((object.ReferenceEquals(this.Recipient_CollectionField, value) != true)) {
                    this.Recipient_CollectionField = value;
                    this.RaisePropertyChanged("Recipient_Collection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SEND_DT {
            get {
                return this.SEND_DTField;
            }
            set {
                if ((this.SEND_DTField.Equals(value) != true)) {
                    this.SEND_DTField = value;
                    this.RaisePropertyChanged("SEND_DT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SEND_ID {
            get {
                return this.SEND_IDField;
            }
            set {
                if ((object.ReferenceEquals(this.SEND_IDField, value) != true)) {
                    this.SEND_IDField = value;
                    this.RaisePropertyChanged("SEND_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ZTB_ORG_ID {
            get {
                return this.ZTB_ORG_IDField;
            }
            set {
                if ((this.ZTB_ORG_IDField.Equals(value) != true)) {
                    this.ZTB_ORG_IDField = value;
                    this.RaisePropertyChanged("ZTB_ORG_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ZTB_SMS_TYPE_ID {
            get {
                return this.ZTB_SMS_TYPE_IDField;
            }
            set {
                if ((this.ZTB_SMS_TYPE_IDField.Equals(value) != true)) {
                    this.ZTB_SMS_TYPE_IDField = value;
                    this.RaisePropertyChanged("ZTB_SMS_TYPE_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="Recipient_Collection", Namespace="http://schemas.datacontract.org/2004/07/LetterService", ItemName="Recipient")]
    [System.SerializableAttribute()]
    public class Recipient_Collection : System.Collections.Generic.List<NewBisPA.LetterSvcRef.Recipient> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LetterSvcRef.ILetterService")]
    public interface ILetterService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILetterService/GetFileControl", ReplyAction="http://tempuri.org/ILetterService/GetFileControlResponse")]
        NewBisPA.LetterSvcRef.LS_FILE_CONTROL_LOG[] GetFileControl(out ITUtility.ProcessResult processResult, System.Nullable<long> applicationId, string office, System.Nullable<long> orgId, string status, System.Nullable<System.DateTime> TrandateFrom, System.Nullable<System.DateTime> Trandateto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILetterService/SelectAppDeatails", ReplyAction="http://tempuri.org/ILetterService/SelectAppDeatailsResponse")]
        System.Data.DataSet SelectAppDeatails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILetterService/DownloadFile", ReplyAction="http://tempuri.org/ILetterService/DownloadFileResponse")]
        NewBisPA.LetterSvcRef.DocumentFile DownloadFile(out ITUtility.ProcessResult pr, long controlId, string downLoadBy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILetterService/DeleteFile", ReplyAction="http://tempuri.org/ILetterService/DeleteFileResponse")]
        ITUtility.ProcessResult DeleteFile(long controlId, string deleteBy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILetterService/UploadFile", ReplyAction="http://tempuri.org/ILetterService/UploadFileResponse")]
        ITUtility.ProcessResult UploadFile(NewBisPA.LetterSvcRef.LS_FILE_CONTROL fileControl, NewBisPA.LetterSvcRef.DocumentFile file, string mailFlg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILetterService/GetAddSetting", ReplyAction="http://tempuri.org/ILetterService/GetAddSettingResponse")]
        NewBisPA.LetterSvcRef.LS_SETTING[] GetAddSetting(out ITUtility.ProcessResult pr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILetterService/SendMail", ReplyAction="http://tempuri.org/ILetterService/SendMailResponse")]
        ITUtility.ProcessResult SendMail(NewBisPA.LetterSvcRef.Mail mail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILetterService/SendSMS", ReplyAction="http://tempuri.org/ILetterService/SendSMSResponse")]
        ITUtility.ProcessResult SendSMS(string MESSAGE, NewBisPA.LetterSvcRef.Recipient[] recipients, int ZTB_SMS_TYPE_ID, int ZTB_ORG_ID, string OFFICE, string SEND_ID, System.Nullable<System.DateTime> SEND_DT, string passKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILetterService/SendSMS_V2", ReplyAction="http://tempuri.org/ILetterService/SendSMS_V2Response")]
        ITUtility.ProcessResult SendSMS_V2(NewBisPA.LetterSvcRef.SMS[] SMS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILetterService/UploadFile_fornewbis", ReplyAction="http://tempuri.org/ILetterService/UploadFile_fornewbisResponse")]
        ITUtility.ProcessResult UploadFile_fornewbis(NewBisPA.LetterSvcRef.LS_FILE_CONTROL fileControl, NewBisPA.LetterSvcRef.DocumentFile file, string mailFlg);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILetterServiceChannel : NewBisPA.LetterSvcRef.ILetterService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LetterServiceClient : System.ServiceModel.ClientBase<NewBisPA.LetterSvcRef.ILetterService>, NewBisPA.LetterSvcRef.ILetterService {
        
        public LetterServiceClient() {
        }
        
        public LetterServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LetterServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LetterServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LetterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public NewBisPA.LetterSvcRef.LS_FILE_CONTROL_LOG[] GetFileControl(out ITUtility.ProcessResult processResult, System.Nullable<long> applicationId, string office, System.Nullable<long> orgId, string status, System.Nullable<System.DateTime> TrandateFrom, System.Nullable<System.DateTime> Trandateto) {
            return base.Channel.GetFileControl(out processResult, applicationId, office, orgId, status, TrandateFrom, Trandateto);
        }
        
        public System.Data.DataSet SelectAppDeatails() {
            return base.Channel.SelectAppDeatails();
        }
        
        public NewBisPA.LetterSvcRef.DocumentFile DownloadFile(out ITUtility.ProcessResult pr, long controlId, string downLoadBy) {
            return base.Channel.DownloadFile(out pr, controlId, downLoadBy);
        }
        
        public ITUtility.ProcessResult DeleteFile(long controlId, string deleteBy) {
            return base.Channel.DeleteFile(controlId, deleteBy);
        }
        
        public ITUtility.ProcessResult UploadFile(NewBisPA.LetterSvcRef.LS_FILE_CONTROL fileControl, NewBisPA.LetterSvcRef.DocumentFile file, string mailFlg) {
            return base.Channel.UploadFile(fileControl, file, mailFlg);
        }
        
        public NewBisPA.LetterSvcRef.LS_SETTING[] GetAddSetting(out ITUtility.ProcessResult pr) {
            return base.Channel.GetAddSetting(out pr);
        }
        
        public ITUtility.ProcessResult SendMail(NewBisPA.LetterSvcRef.Mail mail) {
            return base.Channel.SendMail(mail);
        }
        
        public ITUtility.ProcessResult SendSMS(string MESSAGE, NewBisPA.LetterSvcRef.Recipient[] recipients, int ZTB_SMS_TYPE_ID, int ZTB_ORG_ID, string OFFICE, string SEND_ID, System.Nullable<System.DateTime> SEND_DT, string passKey) {
            return base.Channel.SendSMS(MESSAGE, recipients, ZTB_SMS_TYPE_ID, ZTB_ORG_ID, OFFICE, SEND_ID, SEND_DT, passKey);
        }
        
        public ITUtility.ProcessResult SendSMS_V2(NewBisPA.LetterSvcRef.SMS[] SMS) {
            return base.Channel.SendSMS_V2(SMS);
        }
        
        public ITUtility.ProcessResult UploadFile_fornewbis(NewBisPA.LetterSvcRef.LS_FILE_CONTROL fileControl, NewBisPA.LetterSvcRef.DocumentFile file, string mailFlg) {
            return base.Channel.UploadFile_fornewbis(fileControl, file, mailFlg);
        }
    }
}
