//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewBisPA.DmsExtCallService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Content", Namespace="http://DMSServices.Model/2010/DMSServices")]
    [System.SerializableAttribute()]
    public partial class Content : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] DataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://DMSServices.Model/2010/DMSExternalCallServices", ConfigurationName="DmsExtCallService.DmsExtCallServiceContract")]
    public interface DmsExtCallServiceContract {
        
        // CODEGEN: Generating message contract since the wrapper name (AddNewExtContentRequest) of message AddNewExtContentRequest does not match the default value (AddNewExtContent)
        [System.ServiceModel.OperationContractAttribute(Action="http://DMSServices.Model/2010/DMSExternalCallServices/DmsExtCallServiceContract/A" +
            "ddNewExtContent", ReplyAction="http://DMSServices.Model/2010/DMSExternalCallServices/DmsExtCallServiceContract/A" +
            "ddNewExtContentResponse")]
        NewBisPA.DmsExtCallService.AddNewExtContentResponse AddNewExtContent(NewBisPA.DmsExtCallService.AddNewExtContentRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (GetNextExtBatchNumberRequest) of message GetNextExtBatchNumberRequest does not match the default value (GetNextExtBatchNumber)
        [System.ServiceModel.OperationContractAttribute(Action="http://DMSServices.Model/2010/DMSExternalCallServices/DmsExtCallServiceContract/G" +
            "etNextExtBatchNumber", ReplyAction="http://DMSServices.Model/2010/DMSExternalCallServices/DmsExtCallServiceContract/G" +
            "etNextExtBatchNumberResponse")]
        NewBisPA.DmsExtCallService.GetNextExtBatchNumberResponse GetNextExtBatchNumber(NewBisPA.DmsExtCallService.GetNextExtBatchNumberRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddNewExtContentRequest", WrapperNamespace="http://DMSServices.Model/2010/DMSExternalCallServices", IsWrapped=true)]
    public partial class AddNewExtContentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DMSServices.Model/2010/DMSExternalCallServices", Order=0)]
        public int BatchNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DMSServices.Model/2010/DMSExternalCallServices", Order=1)]
        public string CategoryID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DMSServices.Model/2010/DMSExternalCallServices", Order=2)]
        public NewBisPA.DmsExtCallService.Content Content;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DMSServices.Model/2010/DMSExternalCallServices", Order=3)]
        public int DocNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DMSServices.Model/2010/DMSExternalCallServices", Order=4)]
        public string SecureID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DMSServices.Model/2010/DMSExternalCallServices", Order=5)]
        public int TotalPages;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DMSServices.Model/2010/DMSExternalCallServices", Order=6)]
        public string Username;
        
        public AddNewExtContentRequest() {
        }
        
        public AddNewExtContentRequest(int BatchNumber, string CategoryID, NewBisPA.DmsExtCallService.Content Content, int DocNumber, string SecureID, int TotalPages, string Username) {
            this.BatchNumber = BatchNumber;
            this.CategoryID = CategoryID;
            this.Content = Content;
            this.DocNumber = DocNumber;
            this.SecureID = SecureID;
            this.TotalPages = TotalPages;
            this.Username = Username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddNewExtContentResponse", WrapperNamespace="http://DMSServices.Model/2010/DMSExternalCallServices", IsWrapped=true)]
    public partial class AddNewExtContentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DMSServices.Model/2010/DMSExternalCallServices", Order=0)]
        public string DocumentID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DMSServices.Model/2010/DMSExternalCallServices", Order=1)]
        public int SeqNumber;
        
        public AddNewExtContentResponse() {
        }
        
        public AddNewExtContentResponse(string DocumentID, int SeqNumber) {
            this.DocumentID = DocumentID;
            this.SeqNumber = SeqNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetNextExtBatchNumberRequest", WrapperNamespace="http://DMSServices.Model/2010/DMSExternalCallServices", IsWrapped=true)]
    public partial class GetNextExtBatchNumberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DMSServices.Model/2010/DMSExternalCallServices", Order=0)]
        public string SecureID;
        
        public GetNextExtBatchNumberRequest() {
        }
        
        public GetNextExtBatchNumberRequest(string SecureID) {
            this.SecureID = SecureID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetNextExtBatchNumberResponse", WrapperNamespace="http://DMSServices.Model/2010/DMSExternalCallServices", IsWrapped=true)]
    public partial class GetNextExtBatchNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DMSServices.Model/2010/DMSExternalCallServices", Order=0)]
        public int BatchNumber;
        
        public GetNextExtBatchNumberResponse() {
        }
        
        public GetNextExtBatchNumberResponse(int BatchNumber) {
            this.BatchNumber = BatchNumber;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DmsExtCallServiceContractChannel : NewBisPA.DmsExtCallService.DmsExtCallServiceContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DmsExtCallServiceContractClient : System.ServiceModel.ClientBase<NewBisPA.DmsExtCallService.DmsExtCallServiceContract>, NewBisPA.DmsExtCallService.DmsExtCallServiceContract {
        
        public DmsExtCallServiceContractClient() {
        }
        
        public DmsExtCallServiceContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DmsExtCallServiceContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DmsExtCallServiceContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DmsExtCallServiceContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NewBisPA.DmsExtCallService.AddNewExtContentResponse NewBisPA.DmsExtCallService.DmsExtCallServiceContract.AddNewExtContent(NewBisPA.DmsExtCallService.AddNewExtContentRequest request) {
            return base.Channel.AddNewExtContent(request);
        }
        
        public string AddNewExtContent(int BatchNumber, string CategoryID, NewBisPA.DmsExtCallService.Content Content, int DocNumber, string SecureID, int TotalPages, string Username, out int SeqNumber) {
            NewBisPA.DmsExtCallService.AddNewExtContentRequest inValue = new NewBisPA.DmsExtCallService.AddNewExtContentRequest();
            inValue.BatchNumber = BatchNumber;
            inValue.CategoryID = CategoryID;
            inValue.Content = Content;
            inValue.DocNumber = DocNumber;
            inValue.SecureID = SecureID;
            inValue.TotalPages = TotalPages;
            inValue.Username = Username;
            NewBisPA.DmsExtCallService.AddNewExtContentResponse retVal = ((NewBisPA.DmsExtCallService.DmsExtCallServiceContract)(this)).AddNewExtContent(inValue);
            SeqNumber = retVal.SeqNumber;
            return retVal.DocumentID;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NewBisPA.DmsExtCallService.GetNextExtBatchNumberResponse NewBisPA.DmsExtCallService.DmsExtCallServiceContract.GetNextExtBatchNumber(NewBisPA.DmsExtCallService.GetNextExtBatchNumberRequest request) {
            return base.Channel.GetNextExtBatchNumber(request);
        }
        
        public int GetNextExtBatchNumber(string SecureID) {
            NewBisPA.DmsExtCallService.GetNextExtBatchNumberRequest inValue = new NewBisPA.DmsExtCallService.GetNextExtBatchNumberRequest();
            inValue.SecureID = SecureID;
            NewBisPA.DmsExtCallService.GetNextExtBatchNumberResponse retVal = ((NewBisPA.DmsExtCallService.DmsExtCallServiceContract)(this)).GetNextExtBatchNumber(inValue);
            return retVal.BatchNumber;
        }
    }
}
